### ISSUE TITLE
Cuberite does not compile on FreeBSD

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1043]
http://ci.bearbin.net/job/MCServer%20FreeBSD-x86-64/2/console

**Comment by linnemannr** [comment]
It's not correct to define __POSIX_VISIBLE, this is defined by sys/cdefs.h based on the value of _POSIX_C_SOURCE. I've tried defining that directly, but it is being overridden somewhere else. It might become necessary to build with gcc instead of clang, but I am trying to avoid that.

**Comment by linnemannr** [comment]
Defining _XOPEN_SOURCE=600 yields us _POSIX_C_SOURCE=200112, which yields _POSIX_VISIBLE=200112. This appears to be the correct way to specify the POSIX version, and I can get past building sqlite3. This makes me wonder, though, why does the MCServer build bother compiling third party libraries that can be properly provided by the platform's package system?

**Comment by linnemannr** [comment]
I did get MCServer to build successfully tonight with the FreeBSD port I am working on. I had to patch a few files to make it happen. The most common thing I ran into was the absence of -L/usr/local/lib when needed in linking. In the ports system, I believe this is added automagically to LDFLAGS. In general it doesn't appear that the cmake build honors the environment CFLAGS, CXXFLAGS, or LDFLAGS, which can cause some havoc. I may want to revisit these patches later. tonight I was just interested in getting something to build. Other nuances included the separation of backtrace() into libexecinfo and the need to tell clang not to interpret the unused -L argument warning as an error when compiling the MCServer objs.

Diffs are:

--- ./SetFlags.cmake.orig       2015-02-02 00:27:18.995521211 -0700
+++ ./SetFlags.cmake    2015-02-02 00:46:21.854509101 -0700
@@ -241,6 +241,9 @@
                add_flags_cxx("-ffast-math")
 
                if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
+                       # backtrace() and friends are in libexecinfo
+                       add_flags_cxx("-lexecinfo")
+
                        get_clang_version()
                        if ("${CLANG_VERSION}" VERSION_LESS 3.0)
                                message(FATAL_ERROR "MCServer requires clang version 3.0 or higher, version is ${CLANG_VERSION}")
@@ -254,6 +257,7 @@
                        add_flags_cxx("-Wno-error=shadow -Wno-error=old-style-cast -Wno-error=global-constructors")
                        add_flags_cxx("-Wno-error=float-equal")
                        add_flags_cxx("-Wno-weak-vtables -Wno-switch-enum")
+                       add_flags_cxx("-Wno-error=unused-command-line-argument")
                        if ("${CLANG_VERSION}" VERSION_GREATER 3.0)
                                # flags that are not present in 3.0
                                add_flags_cxx("-Wno-error=covered-switch-default -Wno-error=missing-variable-declarations")
--- ./lib/sqlite/CMakeLists.txt.orig    2015-02-01 21:36:26.478521491 -0700
+++ ./lib/sqlite/CMakeLists.txt 2015-02-01 23:13:59.080739564 -0700
@@ -25,7 +25,7 @@
 
 # FreeBSD requires us to define this to get POSIX 2001 standard
 if (${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
-       add_flags_cxx(-D__POSIX_VISIBLE=200112)
+       add_flags_cxx("-D_XOPEN_SOURCE=600")
 endif()
 
 add_library(sqlite ${SOURCE})
--- ./lib/tolua++/CMakeLists.txt.orig   2015-02-02 00:02:15.029518798 -0700
+++ ./lib/tolua++/CMakeLists.txt        2015-02-02 00:08:57.763510117 -0700
@@ -53,4 +53,8 @@
 target_link_libraries(tolua m ${DYNAMIC_LOADER})
 endif()
 
+if (${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
+       add_flags_cxx(-L/usr/local/lib)
+endif()
+
 target_link_libraries(tolua tolualib lua)
--- ./src/CMakeLists.txt.orig   2015-02-02 00:30:09.560519312 -0700
+++ ./src/CMakeLists.txt        2015-02-02 00:34:15.148516884 -0700
@@ -323,4 +323,9 @@
 if (WIN32)
        target_link_libraries(${EXECUTABLE} expat tolualib ws2_32.lib Psapi.lib)
 endif()
+
+if (${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
+       add_flags_cxx(-L/usr/local/lib)
+endif()
+
 target_link_libraries(${EXECUTABLE} luaexpat jsoncpp polarssl zlib sqlite lua SQLiteCpp)
--- ./src/OSSupport/Errors.cpp.orig     2015-01-13 10:50:24.000000000 -0700
+++ ./src/OSSupport/Errors.cpp  2015-01-25 15:43:10.796511549 -0700
@@ -22,7 +22,7 @@
        
        // According to http://linux.die.net/man/3/strerror_r there are two versions of strerror_r():
        
-       #if !defined(__APPLE__) && ( _GNU_SOURCE) && !defined(ANDROID_NDK)  // GNU version of strerror_r()
+       #if !defined(__APPLE__) && defined( _GNU_SOURCE) && !defined(ANDROID_NDK)  // GNU version of strerror_r()
        
        char * res = strerror_r( errno, buffer, ARRAYCOUNT(buffer));
        if (res != nullptr)

**Comment by worktycho** [comment]
What warnings is it throwing with -Wunused-command-line-arguments? 
And apart from the fact that `add_flags_cxx("-lexecinfo")` needs to be wrapped in a platform check it should be easily apply-able. Would you like to submit a pull request?

**Comment by linnemannr** [comment]
When I added `-L/usr/local/lib` to the CXX flags if the OS is FreeBSD in src/CMakeLists.txt, it gets tacked on to every cc call. With `-Werror`, the compilation steps for the individual objects were throwing a warning that `-L/usr/local/lib` was not being used (because no linking was being done), and that warning became a terminal error. I think what I should do is move that block into the set_exe_flags macro instead.

`add_flags_cxx("-lexecinfo")` is wrapped in a block in set_exe_flags where the compiler is identified as Clang. It's my understanding that this is not FreeBSD specific, but it may be related to Clang version. I'll be double-checking this.

I'll submit a pull request once I'm certain what I've done is kosher. I don't like the idea of hardcoding /usr/local/lib, because in FreeBSD ${LOCALBASE} is not guaranteed to be /usr/local. For FreeBSD builds I think the environment LOCALBASE should be examined, falling back on `make -VLOCALBASE`, and failing that default to /usr/local.

**Comment by worktycho** [comment]
You can probably avoid the warning by using the CMAKE_EXE_LINKER_FLAGS and CMAKE_MODULE_LINKER_FLAGS variable. It should definitely be in set_lib_flags though. We don't have a macro for that though. As for -lexecinfo, what version of clang are you using? I've tested the build on clang 3.1 previously and build regularly with 3.4 on Linux (Travis also tests 3.4). I suspect its an interaction between libclang and FreeBSD meaning its only needed when compiling with clang on FreeBSD.

What you say about why you want to wait sounds extremely sensible. I just thought it looked complete because I don't know FreeBSD.

**Comment by linnemannr** [comment]
I have submitted a pull request with a working set of changes. I decided to just go with /usr/local/lib hardcoded for freebsd for the time being, I can always readdress it later if it becomes an issue. Thanks!

**Comment by SphinxC0re** [comment]
Any updates? Cuberite still doesn't compile on freeBSD

**Comment by Seadragon91** [comment]
I was able to compile cuberite on FreeBSD. I had a linker problem, a missing lib. After I installed it I was able to compile it.

**Comment by Seadragon91** [comment]
Okay the package name is libltdl. Install it with 'pgk install libltdl'. I have FreeBSD 10.2, not sure if this also works on older system.
Also not sure if that is the right way to fix this problem.

**Comment by linnemannr** [comment]
Yes, libltdl is a prereq. I've been working on a FreeBSD port to make install really easy, but I haven't gotten to work on it in a while.
