### ISSUE TITLE
Worrying about anti-cheat...

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#1055]
I mention that we should indeed worry a little about cheating because a friend of mine just came on a test server that I set up and found thousands of exploits like blockspoofing/ -scoping or flying without permission. But I mention not to implement these things into the core plugin and instead implementing it into the server directly, beacause it's faster and cannot be overwritten by other cheaty/ hacky plugins.

**Comment by jan64** [comment]
This might be a bit dated, but i think it's a good idea to mention to Xray here. 
It'd be nice to have something like oreobfuscator in the core server. 
Currently, implementing a fully working plugin for something like this in lua is impossible due to efficiency issues. 
I know it might take a long time, before something like this is implemented, but it's worth a try. :P

**Comment by madmaxoft** [comment]
Actually I believe someone wrote a basic anti-xray plugin; not sure where it is, though.

**Comment by jan64** [comment]
I know about two:
https://github.com/NiLSPACE/AntiX (This method is too slow for anything over 20x20x20 around a player)
and https://github.com/SphinxC0re/SphinxOres (Which i heard did work quite well, but doesn't anymore - i'm going to experiment a bit with it, and see what i can get)

Still, the most efficient solution would be to implement it in c++.

**Comment by SphinxC0re** [comment]
Implementing it in c++ would be a little bit of an overkill. Features implemented in c++ are just for the housekeeping of the server and *real* core functionality

**Comment by SphinxC0re** [comment]
You should directly take this to the forum :) before this derails
