### ISSUE TITLE
Make death messages overridable by a plugin

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1197]
It should be possible for a plugin to provide custom death messages, or to disable death messages altogether.

**Comment by nounoursheureux** [comment]
I got it working by adding a DEATH_MESSAGE hook. I think I'll open a PR tomorrow because I need to clean up my code. I got some questions: 
* Where I am supposed to write the documentation for the new hook ?  
* Is there a way to pass a string to lua by reference ? I couldn't get this to work so I added a new struct `PlayerDeathInfo` containing a string and a `TakeDamageInfo`
