### ISSUE TITLE
Explosion/TnT bugs

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#1219]
- [ ] A double chest stays as a double chest when one of the individual chest blocks that comprise it get destroyed in an explosion and it also keeps its inventory.
- [ ] When placing a block where the second part of the double chest was, all items that where in that half drop on the ground and the chest becomes a single chest.
- [ ] The upper half of a door doesn't get destroyed sometimes and you can open/close it, you cannot destroy it in survival and creative mode.
- [ ] Signs and ladders ignores when the block where there where placed on gets destroyed in an explosion.
- [ ] you can place sings on tnt which gets not destroyed when the tnt is activated
- [ ] explosions can pass. trough obsidian and destroyed blocks get on the top on the obsidian
- [ ] enderchest, anvil and enchanment table gets deroyed from explosions
- [ ] a bed didn't get destroyed fully when one half gets affected by an explosion
- [ ] iron bars sometime ignores explosions
- [ ] tnt can pass trough block whens its activated and moves a few block freely in a random direction

sorry that I'm too lazy to create a new issue for each bug.
I hope that it doesn't include  any duplicate :)

tested with rev bc94ad4b5ae089fe5ee984a827a0575926102bdc (2014_07_18) from my nightbuilds

**Comment by lixfel** [comment]
Tnt passing through blocks could be in different ways.
PrimedTnt would needs an own Implementation of parts of cEntity::HandlePhysics() (currently I didn't understand the code enough to present a solution) because by primedtnt is not the center of the entity important for the colliding, primedtnt collides as a whole block.
![grafik](https://cloud.githubusercontent.com/assets/26159085/23553566/9fc96162-0021-11e7-87b7-50a398f316ce.png)
(the position is red marked where it should be)
but there is one more bug: when the tnt lands on one block, it passes through the block
![2017-03-03_14 47 54](https://cloud.githubusercontent.com/assets/26159085/23553631/f6c21432-0021-11e7-9eb0-c3ddbd4fda7e.png)
(the block is white because of the primed-tnt in it)
these bugs are deadly for every tnt-cannon, so it makes an difference in the gameplay (because i want to play minecraft warship battles (a very ressource-eating mini?game, where cuberite would be the perfect server (without these bugs)))
