### ISSUE TITLE
Cuberite Stats Service

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1690]
I think it would be a good idea for there to be a centralised stats service that can collect information about all the running servers out there.

It would be useful, because it could show the distribution of the different versions of MCServer and plguins and the different locales of users.

I think it should be easy to disable, but on by default, like the MCStats service that bukkit uses. I think it should ping about every hour and include at least this information:
- Unique server identifier (anonymous, just for dedupe)
- Server version string.
- Platform Information
  - CPU Type
  - OS Type
  - RAM Quantity
- Server Uptime
- Number of players online.
- Player cap.
- Plugins enabled.
- Locale

**Comment by yangm97** [comment]
Has any code been done for this?

**Comment by Cl1608Ho** [comment]
No but it's quite easy. When during the startup should a server register itself to a stats service? (I would go without player count and just one single POST requests. Additionally some easy public frontend to show the data in nice graphs. Also I would go without a server identifier and make the server report at its start, so the statistic can tell us still enough, but protects the privacy of the server owners. I think it's a good balance between having as much data as possible and respecting privacy of people. 

For statistical stuff, there is that kind of data masking where the server sometimes pick random values to send to the master server instead of real values because that makes sure you can subtract that from the final statistics but it you look at one specific record, you can't be sure if it's right (protecting their privacy). For example, in case of ram, in 5% of all server launches that the server choose a random number and send that as GB ram (between 1-8 or so).

**Comment by Pokechu22** [comment]
Any reason that the existing [mcstats.org](http://mcstats.org/) service couldn't be used (other than it being down sometimes)?  It's designed for java servers, but it's more or less the standard one and it wouldn't be too odd to use it with cuberite.  [Here's the documentation](https://github.com/Hidendra/Plugin-Metrics/wiki), and I _think_ [the needed code to set up your own instance](https://github.com/Hidendra/mcstats.org).

**Comment by madmaxoft** [comment]
mcstats.org seems non-functional to me right now, so can't really tell.

In any case, **I will veto** any code that implements "E.T. phone home" in Cuberite itself. This added functionality must be provided as a plugin that is by default turned off (opt-in).

**Comment by Pokechu22** [comment]
> This added functionality must be provided as a plugin that is by default turned off (opt-in).

While I agree with it being opt-in, IMO stats should be part of the standard API.  One of the features of mcstats is that you can create custom graphs, but also have access to some default stats.  It would be annoying to need to manually include the same code in a bunch of plugins, and equally annoying to have a bazillion plugins depend upon a stats plugin that must be manually installed.  (I don't think lua plugins have a shading system, which means you can't automatically include it unlike with bukkit plugins).  Plus having it as part of the standard library simplifies configuring with opt in/out, so that only one config can be easily used.

**Comment by Cl1608Ho** [comment]
Just asking, are we planning it as stats for plugins (which is what mcstats is mostly about afaik), or are we talking about stats about cuberite in general?

**Comment by LogicParrot** [comment]
Another point to consider is security. Cuberite is not in a fully stable state yet, and crashes or instabilities are often a sign of exploitable code. Contacting various services opens up those potential vulnerabilities to external parties. I would avoid implementing this until the code is very reliable.

The security concerns amplify the reasons against phoning home by default, but it is not alright regardless.

Yes, I'm looking at you, [cuberite/WorldEdit](https://github.com/cuberite/WorldEdit)

**Comment by NiLSPACE** [comment]
Could you elaborate on that? I'm trying to keep WorldEdit as stable as possible.

**Comment by madmaxoft** [comment]
I think he means the default value to check for updates.

**Comment by LogicParrot** [comment]
Cuberite itself is probably exploitable. The default value is checking for updates should be off for that reason (and for other reasons as well)

**Comment by mathiascode** [comment]
This is probably not something we will pursue at this point, since we already disabled our web analytics server.
