### ISSUE TITLE
Placing some blocks doesn't remove them from player inventory

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#1700]
I placed a chest in survival mode and it don't get removed from player inventory.

**Comment by madmaxoft** [comment]
Good catch, this is probably a bug in my rewrite of the block placement. I have a feeling that there will be more cases like this - beds, slabs, tall flowers...

**Comment by Seadragon91** [comment]
Okay I tested the blocks and here is a list, not sure If I got all:
```
bed
large fern
double tall grass
peony
rose bush
lily pad
sunflower
lilac
all doors
```

**Comment by hirnwunde** [comment]
same here with birch door

**Comment by tigerw** [comment]
So the problem here is that with the new refactoring, if OnPlayerPlace is overridden, a bunch of other functionality originally in it (sound, item removal), may or may not carry over into the override, depending on how forgetful your programmer today is (http://xoft.cz/personal.html).

Copying the relevant code to every override results in code duplication. Suggested remedy: adapt GetPlacementBlockTypeMeta to take a sSetBlock vector reference, for ItemHandler and BlockHandler. Since every override so far is just for multiblocks (doors, beds), this is good.

Additionally, remove ItemHandlers from non-items such as chests, and move their code to BlockHandler.

**Comment by Seadragon91** [comment]
Okay, this is not then anymore easy. I think or?

**Comment by tigerw** [comment]
I would say a medium to fix properly.

**Comment by Seadragon91** [comment]
I think this should be added to the surival milestone, or?

**Comment by Nixtren** [comment]
While we wait for madmaxoft to fix the bug, here's a plugin to temporarily fix this problem:
https://gist.github.com/Nixtren/fc4bdb51d3a11a6431a7
Thanks to Seadragon91 for the tiny list of bugged items :)
