### ISSUE TITLE
Mobs spawning in Water

### ISSUE THREAD

**Issue by Knochi** [cuberite/cuberite#1753]
Hi
I got my MCServer running on a Raspberry PI.
One annoying bug is that a lot of mobs (creepers, cows, pigs) are spawning in the water.
I downloaded the binary for Rapberry Pi last week.
![2015-02-19_14 26 57](https://cloud.githubusercontent.com/assets/5979046/6267426/2928e69e-b844-11e4-867b-32161c3d34bc.png)

**Comment by Masy98** [comment]
I don't think they are spawning there. I don't know why but mobs seem to like to walk into the water. The only problem with this is that they freeze and aren't able to move in water :)

**Comment by Knochi** [comment]
Hmm I never saw any mob going into the water. The are just there. 
And where they are they are struggling without moving. 
Looks like they are drowning.

**Comment by LO1ZB** [comment]
@Masy98 they are spawning in the water, I even saw mobs spawning in the middle on an ocean.

**Comment by Defkil** [comment]
on my Server (Debian) i have the problem, too

**Comment by Masy98** [comment]
okay, i never really worked with my own MCServer. I mostly just help Howaner testing things and then i play around with stuff. At that time i only saw mobs walking into the ocean, not spawning there...
Again, i kinda quitted MCServer because the stuff that i am able to do (i can't code :D) i have already done, like alphasorting lists and adding recipes and stuff.

**Comment by Kellerkind85** [comment]
Can sign this one too.
Strange thing to watch a horde of sheeps swimming in the Ocean.

**Comment by SpockMan02** [comment]
Plus, their heads always seem to be down.

**Comment by mathiascode** [comment]
While mobs still spawn in water at times, it doesn't seem to be as big of an issue as described here.
