### ISSUE TITLE
SIGSEGV: Segmentation fault

### ISSUE THREAD

**Issue by elgholm** [cuberite/cuberite#1838]
Can you enable extensive logging somewhere?
My server crashes, see below, not really helpful. Maybe I could enable more verbose logging?

Log tail:

```
info [21:12:05] [Cevin3241]: zzZzZzZZzZzZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
info [21:12:05] [HammarbyElias]: zzzzzzzzzZ
Err  [21:17:31]   D:    | MCServer has encountered an error and needs to close
Err  [21:17:31] Details | SIGSEGV: Segmentation fault
Err  [21:17:31]   D:    | MCServer has encountered an error and needs to close
Err  [21:17:31] Details | SIGABRT: Server self-terminated due to an internal fault
```

**Comment by madmaxoft** [comment]
If the server crashes, it generates a core dump (unless your system is configured not to produce dumps); those can be used to gather more information. Check the output of `ulimit -a` command, if you see core files disabled (size 0), use the `ulimit -c unlimited` command to enable the core dumps.

Generally, there's no safe way for a C++ program to generate any kind of logging information once it crashes. We just include a generic message because that works in the most cases.

**Comment by Seadragon91** [comment]
Closing because it's old and no more information.
