### ISSUE TITLE
Nether: spawners, dungeons, portals and water

### ISSUE THREAD

**Issue by cafehaine** [cuberite/cuberite#1856]
With default generator:
Blaze spawners are pig spawners
Dungeons don't have any chests/rooms with nether wart
Portals are not created when we enter from overworld
We can place water in nether

**Comment by NiLSPACE** [comment]
If you change the water simulator to `vaporize` then you can't place water. This should be part of the default configuration though.

**Comment by NiLSPACE** [comment]
Dungeons do have nether wart rooms and chests. The chest do not have any content though.

**Comment by madmaxoft** [comment]
Additional bug in portals: they don't link together. When you create a portal in the Nether and travel back to the overworld, you will not teleport to the original overworld portal
(reported in http://forum.mc-server.org/showthread.php?tid=1923 )

**Comment by SphinxC0re** [comment]
Also the travel through a newly created portal should create another portal on the other side

**Comment by NiLSPACE** [comment]
I've been wondering how we're going to detect nether portals. Maybe instead of scanning a whole chunk we could check in a checkerboard method, since a portal is at least 3 blocks wide (in MCServer, Vanilla has the minimal set to 4).
```
X: Checked
Z: Not Checked
X Z X Z X Z X Z X Z X Z X Z X
Z X Z X Z X Z X Z X Z X Z X Z
X Z X Z X Z X Z X Z X Z X Z X
Z X Z X Z X Z X Z X Z X Z X Z
X Z X Z X Z X Z X Z X Z X Z X
etc
```
That way you would always find the portals, but with half the amount of blocks checked. Or is there a different method to detect netherportals?

**Comment by lkolbly** [comment]
I'm new to MCServer, just poking through it a little bit.

What if the chunks (or maybe the world?) stored a list of nether portals? It wouldn't be too terrible to add them in Blocks/BlockFire.h's FindAndSetPortalFrame, since it already knows where portals are. Then cEntitity::DoMoveToWorld could validate the portal and make sure the portal's still there, and if it isn't it could remove it from the list. (Vanilla Minecraft seems to do a similar thing, according to the minecraft wiki there's a 60-second cache of nether portal targets - so presumably they're caching these linkages somewhere)

Another thing that needs to be done is to multiply the entity's coordinates by 8 when switching between the overworld and the nether. Would this be best done as a function in the cWorld which translates coordinates from a world to its own coordinate space?

I have some downtime this week, I can take a look at this if nobody else already has plans to do so.

**Comment by NiLSPACE** [comment]
It is of course possible to keep a list, but where would it be saved? And what would happen if you would import a world from vanilla? It wouldn't have such a list, so would those portals not work at all?

**Comment by lkolbly** [comment]
Good point. Could the list be saved in the <world>/data/ folder? I'm not sure how closely you guys want to stay to the vanilla world format.

When a world is imported from vanilla (I'm not 100% sure how that works), it could be scanned for nether portals. Presumably that's a one-time operation, so taking a while wouldn't be the worst thing in the world, and we could do a checkerboard thing like you said above to speed it up.

**Comment by lkolbly** [comment]
I'm assuming that converting from vanilla to MCServer is a distinct operation, and MCServer doesn't just run off of a vanilla world. If it does than I don't think it'd work.

**Comment by worktycho** [comment]
It sort of does. We mostly use the vanilla storage, but some things are stored differently, for example we store player data differently.

**Comment by worktycho** [comment]
So storing it as part of the chunks is not really an option.

**Comment by lkolbly** [comment]
Fair enough. Would it be reasonable to add a world/data/portals.dat file, and scan the chunks at load time if it doesn't exist?

I feel like scanning the nearby chunks at runtime would be a performance hazard, since even with the checkerboard method above we'd have to check 1M blocks (128*128*256 / 4) every time a portal is crossed. I may be wrong though.

**Comment by worktycho** [comment]
Its possible, but you then have to work out the format for the portals.dat, and work it into the chunk loading pipeline. I agree with you about scanning, so even scanning on chunk load would be better.

**Comment by worktycho** [comment]
Also I took the liberty of updating your comment to fix the markdown.

**Comment by worktycho** [comment]
One possibility for the format would be to use an sqlite database.

**Comment by lkolbly** [comment]
A sqlite database would let us index the portals by X and Z coordinates, so that'd be good.

**Comment by lkolbly** [comment]
It might be able to run in the cWorld constructor, right after the scoreboard loads. It could check if portals.sqlite exists, and if not it could spin off a thread to scan the world and build the database. The downside of that is that nobody would be able to use a nether portal for the first few seconds after a vanilla world is loaded, but that may be okay? Depends on the performance of the scanning, and it could potentially prioritize areas where players are.

The trick is that I'm not sure we can do the scan when a chunk is loaded, because the entity needs to know the coordinates of the destination portal before it changes worlds. I think. I might be wrong.

**Comment by worktycho** [comment]
It might work or might not. I think that you would need to do some experimentation to see whether the initial scan was possible, but I think there'd be trouble with the world storage abstraction. Running the scan on load can work, because the edge case of going into a portal on load merely degrades into the current situation.

**Comment by lkolbly** [comment]
I'll do some experimenting and see if it's possible.

**Comment by madmaxoft** [comment]
I think an on-chunk-load scan is a better approach. Currently the storage subsystem provides no means of enumerating chunks that are present, so you can't really have an operation that says "for each chunk in the world..." When a player walks through a portal, they are guaranteed to have the chunk loaded, so it has already been scanned for portals; the destination chunks can be scanned when the `cChunkStay` for the destination world is being populated.

If vanilla indeed stores the portal data somewhere, it would be better to adapt their format; I believe most, if not all, vanilla files have already been documented somewhere; mostly they just use gzipped NBT anyway.

**Comment by tigerw** [comment]
To remain simple, I suggest to just scan on portal entry. I believe that maintenance of a list of valid portals may be more cumbersome to implement, and may be more bug-prone.

**Comment by worktycho** [comment]
Problem is that its relatively slow, looking at memory bandwidth its a 1MB block which takes ~100µs which is ~1% of a ticks available time. Maintaining a list allows much faster portals.

**Comment by worktycho** [comment]
It also allows the potential of plugins overriding the links.

**Comment by lkolbly** [comment]
If we used a cChunkStay, though, could we move the hard labor out of the tick thread if it becomes an issue? Because we're going to need to do a scan anyway sometimes, in the event that the portal doesn't exist we have to scan to find an open area which is big enough.

I think vanilla MC's portal cache is in-memory, which is fine since it's just for 60 seconds anyway. I assume it does a full scan once that cache is expired, but I don't know.

**Comment by worktycho** [comment]
It wouldn't be worth it. the main work is reading the blocks, and that has to be done with the World lock held.

**Comment by lkolbly** [comment]
Oh, okay. A cChunkStay for the 256x256 area around the nether portal would still be useful.

**Comment by lkolbly** [comment]
I would think. Maybe.

**Comment by lkolbly** [comment]
Also that would load the chunks that we need to scan?

**Comment by madmaxoft** [comment]
Exactly, you can't do the scan without a `cChunkStay`.

I'd suggest scanning only every third slice, Y-wise (Y = 1, then Y = 4, then Y = 7 etc.) since each portal is at least 3 blocks high. This should improve the scanning speed, if the memory prefetcher is smart enough to detect this usage and preload the correct data into the cache.

**Comment by NiLSPACE** [comment]
@madmaxoft that with [this](https://github.com/mc-server/MCServer/issues/1856#issuecomment-100502183)?

**Comment by madmaxoft** [comment]
That wouldn't help too much, because those bytes are right next to each other so they will still be loaded in the cache, there's very little savings in that.

**Comment by NiLSPACE** [comment]
Though it would would require less checks.

**Comment by lkolbly** [comment]
So I sketched out a quick POC: https://github.com/lkolbly/MCServer

It uses a cChunkStay which triggers in the middle of cPlayer::DoMoveToWorld (obviously I need to refactor it so all Entities can use it, but for right now just the player uses it).

The issue I see is that the cChunkStay generates chunks, which takes ~20 seconds to generate the needed 256 chunks. Once the chunks are generated, though, there doesn't seem to be a perceptible lag in scanning the chunks, at least not that I can tell.

I'm not sure what the right way to fix this would be. I'm poking around with modifying cChunkStay to have a "don't generate chunks" option, since we know that any existing nether portals are in generated chunks. Then if there is no existing nether portal we can have a smaller cChunkStay to build a portal. Does that seem like a reasonable fix?

**Comment by madmaxoft** [comment]
There's no need to fix that, since the chunks need to get generated anyway - the player will be moved there and will request the chunks anyway. This is actually a good thing, as long as the delay is handled properly in the client - the player needs to be sent a packet that displays the "Entering nether" screen, then the chunkstay processing needs to take place, and finally the player needs to reappear in the Nether.

Of course, your code only handles the Overworld -> Nether direction, you need to modify it for both directions. Also it needs to be specific for Overworld <-> Nether worlds. Since MCS supports multi-world, it's perfectly possible to have two Overworlds, and teleporting between them shouldn't affect the coords.

This all brings me to an idea - the ChunkStay processing shouldn't be done in the `DoMoveToWorld()` function, but rather it should be in the nether portal detection code and it should trigger the `DoMoveToWorld()` internally for the actual move, instead of the other way around.

Also note that we wanted to give `MoveToWorld()` extra parameters specifying the new coords in the destination world, this might be the perfect chance to do that.

One final note: please do try to conform to our coding style - spaces around math operators (`x&1`), descriptive parameter names with `a_` prefix (`a_BlockX` instead of `x`) etc. Don't pull `cChunkMap` out of the `cWorld` instance, either go through `cWorld`, or use a `DoWithChunk` to pull the chunk modify it directly.
