### ISSUE TITLE
Igniting TNT while block above makes the TNT move up

### ISSUE THREAD

**Issue by Rakete1111** [cuberite/cuberite#2093]
When you ignite a TNT while a block is above, the TNT will jump to the nearest possible place on the Y axis. This is probably caused by an entity collision test for the TNT block

**Comment by NiLSPACE** [comment]
That is for falling blocks as well I believe.

**Comment by rekuen** [comment]
It also happends with no block above, I've tried to make tnt cannons a thousand times, and it impossible due to this issue, when you light a tnt it move as you said to the Y axis and one block up in my case when is above water.

**Comment by D4N** [comment]
I have looked into this issue and it seems partially solved. If you put a normal block above a TNT block and ignite the TNT it seems to work just fine. But if the block above the TNT is a block affected by gravity (like sand, gravel, etc.), things don't work out perfectly. Once the TNT is ignited, it turns into an entity and the block above it falls into the TNT and pushes it to the side. If there are other blocks surrounding the TNT, then the TNT block appears somewhere above original position. However, in vanilla gravity affected blocks fall simply into the ignited TNT and don't move it to the side.
I have looked over the source code and i guess a good place to start might be `cEntity::HandlePhysics(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)`
(from src/Entities/Entity.cpp). Maybe add another condition for ignited TNT?
With a bit of guidance, I can create a PR.

**Comment by madmaxoft** [comment]
If I understand that right, what you're reporting is that a falling block entity pushes other entities away from it, while it shouldn't. Is that so?

In such a case, probably the cleanest solution would be to have a flag whether an entity should push other entities around, and turn it off for falling block entities (and possibly others? pickups? projectiles?)

**Comment by D4N** [comment]
Well a falling block should push at least items out of its way but i think not mobs. So I think a simple flag would not be enough, since it would depend on the type of entity onto which the block falls.

**Comment by D4N** [comment]
I have tested what happens when a block lands on mobs and items, and apparently in cuberite both are pushed out of the block, while in vanilla only the items are pushed out, mobs on the other hand stay in the block. I guess this is a related bug?

**Comment by D4N** [comment]
I have made a very simple change (see D4N/cuberite@2119615e9372e56deea91d1b27a5fa0d1567eb28) which mostly fixes the issue for ignited TNT blocks. However TNT blocks still jump too much to the side when ignited compared with vanilla. Unfortunately I have not yet identified the code responsible for the kick that the TNT block gets once it turns into an entity.

But falling blocks still have some additional bugs, for instance without the fix, a mob is pushed out of a fallen block instead of staying inside it (and possibly taking suffocation damage). However, I don't think the simple fix solved that completely, since I observed that a creeper inside two sand blocks jumped onto the first and then onto the second (thereby evading its death). Also anvils don't damage mobs, when they fall onto them (see #2334).

So I guess to fully address all the issues, maybe the entity class could get a virtual function that is responsible to handle when an entity is inside a block and each entity type could implement it on its own when some special behaviour is required? (For instance deactivate walking for mobs, being pushed out for TNT, etc.)

**Comment by Pokechu22** [comment]
> Unfortunately I have not yet identified the code responsible for the kick that the TNT block gets once it turns into an entity.

[`cWorld::SpawnPrimedTNT`](https://github.com/cuberite/cuberite/blob/759618b0356a357d06a89f4348437a8de52d2078/src/World.cpp#L2331-L2335)

**Comment by denmark111** [comment]
When compared to vanilla minecraft, TNT jumps too much when ignited in cuberite.
I think it has to do with `a_InitialVelocityCoeff` in [cWorld::SpawnPrimedTNT](https://github.com/cuberite/cuberite/blob/759618b0356a357d06a89f4348437a8de52d2078/src/World.cpp#L2331-L2335) as Pokechu22 already pointed out.  
I'm about to test it out, should be able to get rid of that weird 'kick' after ignition.  

But the problem with interaction with other entity is related with collision detection in  
`cEntity::HandlePhysics(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)`  
which is, again, already pointed out by D4N.  
Judging by the comment `//TODO Add collision detection with entities.` maybe this is the reason  
why some entities not begin able to interact just yet?

BTW, I'm new to github, and came across this awesome repo while doing some github search about C++ projects.  
I am really interested in this project cause I use to play minecraft a lot with my friends and was always curious about how minecraft server works.  
I'm still learning C++, and not as skilled as you guys here so I might ask some silly questions. Hope you understand:-)  
감사합니다~
