### ISSUE TITLE
Spawn position

### ISSUE THREAD

**Issue by warmist** [cuberite/cuberite#2223]
Spawn position is not read from ini (or nbt). /setspawn does nothing.

**Comment by madmaxoft** [comment]
Are you sure about this? It has worked, like, always.
Note that once a player logs into the server, changing the spawn position in world.ini doesn't affect that player, because they already have their position saved in the player data file. You'd need to remove the player data file (or kill the player) in order to spawn back at the world.ini's spawn coords.

**Comment by warmist** [comment]
Tried /setspawn and /kill did not change spawn pos.
Tried setting ini and deleting world (including player data) restarting the server and it still did not work.

**Comment by warmist** [comment]
Also found this: https://github.com/tonibm19/Fixes
It "fixes" core bug with set spawn not working, and just teleports to the spawn so it looks like there are some workarounds?

**Comment by bearbin** [comment]
Closing as outdated, and the code in that area has been replaced now.
