### ISSUE TITLE
Mac build fails on OSX 10.10

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2327]
I'm working on fixing it, but I need some advice.
Here's the errors I am struggling with right now:
```
/Users/barneys2/GitHub/cuberite/src/Protocol/Protocol18x.cpp:143:39: error: cannot initialize a parameter of type 'const Byte *' (aka 'const unsigned char *') with an lvalue of type 'const char *'
/Users/barneys2/GitHub/cuberite/src/Protocol/Protocol18x.cpp:144:20: error: cannot initialize a parameter of type 'const char *' with an lvalue of type 'Byte [512]'
/Users/barneys2/GitHub/cuberite/src/Protocol/Protocol18x.cpp:2228:56: error: static_cast from 'cProtocol180 *' to 'uintptr_t' (aka 'unsigned long') is not allowed
/Users/barneys2/GitHub/cuberite/src/Protocol/Protocol18x.cpp:2278:37: error: static_cast from 'cProtocol180 *' to 'intptr_t' (aka 'long') is not allowed
```

Any advice with how to fix them? I've just been trying to use `static_cast` and `reinterpret_cast` where needed, but none of the c++ template casts allow the conversion.

**Comment by NiLSPACE** [comment]
Related to #2325?

**Comment by SamJBarney** [comment]
Yeah

**Comment by SamJBarney** [comment]
I've got all of the errors fixed except for the ones in Protocol18x.cpp. I can shut them up if I add `-Wno-error=old-style-cast` to the Cmake file, but I was wondering if there is a better way.

**Comment by madmaxoft** [comment]
The first two should be easy with `reinterpret_cast`, the other two I don't know, really.

**Comment by worktycho** [comment]
The second two are the result of using `this` as the nonce. I'm slightly horrified at this code, and would recommend that we rewrite it to use a crypo random number. However I can see that the knock on effects would cause a lot of problems, because that needs to be stored by cClientHandle for various reasons. That in turn means that we are now storing a number of bytes of useless memory for each player for most of its lifetime. Ideally we would split cClientHandle to have separate instances for each state in the state machine, but thats a lot of work, and will probably not happen.

**Comment by tigerw** [comment]
> I'm slightly horrified

I believe this is the first time I've seen Tycho say that. r/mildlyinteresting

**Comment by worktycho** [comment]
Off topic: I'm sure I've said worse about code in the past. Its just I tend to reserve stronger descriptions for code that does much worse things. Have you ever seen code which uses the same name for two global variables and a type, but with variations in capitalization? Or did you know that no one has successfully run openSSL under valgrind?

**Comment by tigerw** [comment]
> I'm sure I've said worse about code in the past
About my code, definitely :P

>  Or did you know that no one has successfully run openSSL under valgrind?
Doesn't OpenSSL intentionally do some things which Valgrind warns about?
