### ISSUE TITLE
Suggesting: Multiple repos and multiple version branches

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2408]
Instead of having a singular repo, use two:
cuberite-core: Contains code that is used across all versions of cuberite, such as world generation, world loading/unloading, etc.
cuberite: Has multiple branches, each which contains code specific to a particular version of minecraft. So, cuberite-1.7.10 would have code that is necessary for a complete 1.7.10 experience, and cuberite-1.8 would contain all 1.7.10 code along with anything that was 1.8 specific. The same would go for 1.9.

I think this would be a good idea to simplify the protocol handling code, allow us to support multiple versions without a whole bunch of handling code, and allow people to choose which version they want to use.

**Comment by madmaxoft** [comment]
I vote against this. First, the multiprotocol support is cool, no other server has it. Second, it will still need to be kept if we want interoperability between desktop and PE or Win10PE clients. Third, it's a very thin layer with almost zero performance overhead and almost zero maintenance, so why touch it at all? If it ain't broken, don't fix it.

Now why two repos wouldn't work:
- World generation can use blocks not available in older clients
- The comon code would still need to keep common interface so that the individual versions compile correctly; but this time the compiler won't check this, so if you change the interface and forget to change an old protocol, you give us broken code.

**Comment by SamJBarney** [comment]
Ok. Good thing it was just a suggestion.
