### ISSUE TITLE
enderman doesn't attack you

### ISSUE THREAD

**Issue by dscso** [cuberite/cuberite#2472]
if you hit or look in the eyes of a Enderman, he won't hit you.

**Comment by aberts10** [comment]
Ive noticed on my server lots of enederman that teleport every 10 seconds and are like ghosts, they live during the day, and they are always teleporting.

**Comment by NiLSPACE** [comment]
They are not actually teleporting. That's the problem. It looks like they are teleporting because Minecraft expects them to.

But when Minecraft "teleports" the enderman and Cuberite then says "no, the enderman just walked 0.0512.. blocks away from it's previous position" Minecraft teleports the enderman back. 

This repeats itself over and over making it look like the enderman is drunk teleporting to lots of places.

**Comment by SafwatHalaby** [comment]
Related: https://github.com/cuberite/cuberite/issues/2448
