### ISSUE TITLE
What is the purpose of a cChunkLayer?

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#2559]
During browsing, I became confused on the presence of the above class. What are chunk layers? They don't appear to form part of @worktycho's chunk sparing refinements since they were there before that commit. Wouldn't it be much simpler if cChunkMap described just a map of chunks, as opposed to a list of "chunk layers" redirecting to a list of chunks (which are not even actual layers of a chunk)?

**Comment by NiLSPACE** [comment]
The way I see it is that it's splits up the array of chunks. Instead of having an array with 300 chunks you'd get 30 arrays containing 10 chunks. I don't know why, but it's possibly a speedup of some sorts.

**Comment by madmaxoft** [comment]
It is unfortunately named. It groups neighbor chunks together, much like the Anvil fileformat does (32 * 32 chunks per one instance of a `cChunkLayer`). This speeds up block-to-chunkptr and chunk-to-neighbor lookups significantly

**Comment by NiLSPACE** [comment]
Perhaps we should rename it then? Does `cChunkGroup`, or `cChunkCluster` make sense?

**Comment by SphinxC0re** [comment]
another rename :smile:

**Comment by NiLSPACE** [comment]
Yes, but <sup>this<sup>is<sup>different</sup></sup></sup>

**Comment by SphinxC0re** [comment]
<sub>I <sub>k<sub>n<sub>o<sub>w

**Comment by madmaxoft** [comment]
`cChunkChunk` :)

**Comment by SphinxC0re** [comment]
```cBunchOfChunks```

**Comment by tigerw** [comment]
> This speeds up block-to-chunkptr and chunk-to-neighbor lookups significantly.

Is there any performance data for this? Purely conjecture, but considering a map approach vs. current:

-----

block-to-chunkptr
`block coordinates → (chunk position) → map lookup`

versus

block-to-chunkptr
`block coordinates → (chunk position) → (layer position) → linear search → (position in layer) → array lookup`

-----

If anything, there's an unnecessary search in there.

**Comment by madmaxoft** [comment]
Note that this is ancient code, it predates my involvement with the project. Also note that a simple hashmap will not suffice - due to hashing collisions you'd need to be able to store multiple chunks with the same hash, thus enlarging your original chain:
`block coordinates → (chunk position) → map lookup → linear search`
Depending on the hashing function, the linear search could be order of magnitude more work than the one in the "layered" scenario, which most of the time consists of a few comparisons, there are hardly ever more layers than four.

With more items in the (multi)map, the housekeeping of the map (adding and removing chunks) could become substantial as well. Locating items will, too, become more work then - depending on the multimap implementation; if it is something like a tree, it will have an O(log(N)) depth, which means O(log(N)) comparisons on average to reach an item; with 400 loaded chunks this is 9 comparisons per lookup - much more than the layers' four. Cache locality is yet another thing, the map is going all over the place, while the layers are small and quite almost never evicted from the cache.

Unfortunately there's no real performance data. I would for sure be interested in a comparison, although it might be difficult to come up with a reasonable usecase to test it consistently.

**Comment by tigerw** [comment]
So essentially cChunkLayer is an implementation of a bucket map, and you're saying that this is better because of the *implementation of unordered_map* is slow?

That's really unfortunate, because cChunkLayer is not the most obvious piece of code in the codebase, and I'm a great believer of letting the compiler do the optimisations :(

**Comment by LogicParrot** [comment]
What is the reason behind dividing `cChunkMap` into `cChunkLayer`s which are divided into `cChunk`s? 
Whatever the reason is, does it justify the disadvantage?: Random chunk access is `O(Layer Amount)`. This means that all `DoWithChunkByX` are inefficient. A chunkmap having a hash table (`std::unordered_map`) of chunks would be practically `O(1)`. 
Following the same reasoning, I think we should have a `unique id > entity pointer` hash table at cWorld. This would be a performance boost for the `doWithXByUUID` functions.

I did not perform any benchmarks, but I think it's possible that these functions would be pretty slow when a sufficient amount of players are logged in at the same time.

**Comment by LogicParrot** [comment]
>there are hardly ever more layers than four.

Mind elaborating?

**Comment by LogicParrot** [comment]
>chunk-to-neighbor lookups significantly

Mind elaborating? Can't we use the m_NeighborXX for traversing neighbrs?

**Comment by LogicParrot** [comment]
Does the std standard implement [inceremental rehashing](https://en.wikipedia.org/wiki/Hash_table#Dynamic_resizing)?

**Comment by LogicParrot** [comment]
>Depending on the hashing function, the linear search could be order of magnitude more work than the one in the "layered" scenario

Note that after #3151 , the amount of loaded chunks would be static (`MaxLoadedChunks`) This means that:
- No rehashing is ever needed
- If we have a big enough hash table, e.g. 2 or 3 times bigger than the max number, then collisions are practically not a concern and it's true `O(1)`.

**Comment by tigerw** [comment]
#2565 ?

**Comment by LogicParrot** [comment]
@tigerw thanks :)

If data locality and such are a concern, one alternative middle-ground solution would be simply keeping the layers but storing them in a hash table rather than a linked list.

**Comment by worktycho** [comment]
I'd be surprised if data locality was a concern. cChunk is a large object and contains a lot of references, so looking up neighbors is unlikely to benefit from locality. The std::map implementation is worth looking at.

**Comment by LogicParrot** [comment]
Worth looking into indeed. Still, I can see a potetial benefit for Layers: chunks in a 32 x 32 area are very likely to be all (or most) loaded or unloaded. Having an unordered map of such layers means there would be far less elements in that map, a thousand times less at best.

**Comment by worktycho** [comment]
With unordered_map the number of elements is does not effect lookup time, and the memory usage from the increased number of elements is minimal (`32 * 32 * 8 = 8KiB`) per layer, Which is less than the memory used by chunklayer objects unnecessary pointers if the layers are < 50% used on average.

**Comment by LogicParrot** [comment]
Yes. Sorry. My comment would be relevant for a *map* though.

**Comment by LogicParrot** [comment]
See #2559

**Comment by LogicParrot** [comment]
See #3153

**Comment by worktycho** [comment]
The layers save 9 nodes of depth in GNU libstdc++ map. Possibly worth keeping.

**Comment by madmaxoft** [comment]
The class has been removed from the source code. Closing.
