### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [cuberite/cuberite#2653]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [cBioGenCache](https://github.com/cuberite/cuberite/blob/baca82cce791132d01dcba376c2869748aa942e5/src/Generating/BioGen.cpp#L52 "cBioGenCache class")
* [cCompoGenCache](https://github.com/cuberite/cuberite/blob/baca82cce791132d01dcba376c2869748aa942e5/src/Generating/CompoGen.cpp#L341 "cCompoGenCache class")

**Comment by madmaxoft** [comment]
unique_ptr is not a valid replacement, since the data is an array.

**Comment by worktycho** [comment]
unique_ptr has a specialization that handles delete[] for arrays. Whats more of a problem is reading through all code that uses the memory and checking that the memory does not escape the object, and that the smart pointer will not change the semantics of where memory is deletion. I have several times identified memory that looks from the declaration to be a good candidate for conversion to smart pointers only to find the code passes it somewhere else. If you are willing to go through this, I would accept a PR.

Also exception safety is not important, because we do not use exceptions. If the std lib throws an exception then we are going to abort, so deleting memory is useless.

**Comment by LogicParrot** [comment]
This is a long term goal and requires a long term, gradual fix.
