### ISSUE TITLE
Block breaking denied, but player can slip trough

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2669]
Example
Block breaking denied with plugin.
Player can still fall trough the ground, if he break the block under his feet.

**Comment by Schwertspize** [comment]
one player said, that eg wallhack does work. maybe its a problem that the client thinks, it can break the block, predicts, that he falls down and sends that to the server and the server "let the player be there"

**Comment by SphinxC0re** [comment]
This problem can't be handled by the serve itself. If you want to build a noclip protection, you need to handle these kinds of exceptions yourself. So you could save the positions of the player and rollback to a known position if the block is not breakable.

**Comment by Schwertspize** [comment]
why cant the server handle it? i mean you should check if the blockbreaking hook returns true and if so, check if the position is still valid

**Comment by SphinxC0re** [comment]
No because there might be a case where this behavior is wanted

**Comment by SphinxC0re** [comment]
We don't want to take control over the devs plugins

**Comment by Schwertspize** [comment]
ah ok... but maybe we want a "core like" plugin with basic anti cheat functions.

**Comment by SphinxC0re** [comment]
We already had this discussion in another thread. I'm not going to discuss this topic further in here

**Comment by madmaxoft** [comment]
The core problem of this issue is that the server doesn't handle player physics. *At all*. It uses whatever position the player sends, without much validation. We'd need to implement physics, and a set of rules to specify how far away we allow the player-sent coords to be from the calculated ones, and how much the players can cut corners etc. This is difficult, even vanilla doesn't do it to everyone's satisfaction (ever tried walking around tight corners just to be reset back to previous coords by the server?)

**Comment by LogicParrot** [comment]
This is not the same as cheating. Cheating is harder to handle.

But the server **can** and **should** handle this. Client reports a block breaking > break denied > send the player back to where he was before block breaking.

@SphinxC0re when is such a behavior wanted?
