### ISSUE TITLE
Player heads are broken on servers with authentication off

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#2888]
After this PR (#2855) was merged, I can no longer create custom player heads on my server without crashing my client. This only happens when the server is in offline mode.

Here is the crash message: http://pastebin.com/RHDDe2BV

Also, I don't like that you can't create player heads of players that are not online on the server. This worked fine before.

**Comment by bibo38** [comment]
First of all: How did you produced the crash? Can you give a way to reproduce this?

To the main problem: In Minecraft 1.7 the Server only send the Name of the player to the client for a player head, but in Minecraft 1.8, the server need to send **the whole skin** to the client, which creates the problem of obtaining the skin data.
But in the current implementation, the player must be online(and online-mode=true), because this allows the server to grab the skin data from the current client.

The current PR is only dedicated to allow the use of player heads in Minecraft 1.8 again, but the logic to get any players skin will be implemented in the future.

**Comment by mathias-github** [comment]
I produced the crash by using the /skull command in Essentials.
