### ISSUE TITLE
Potential use-after-free in mob code

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2896]
If an entity is killed while a monster is targeting it, it will be freed in:
https://github.com/cuberite/cuberite/blob/85e534b745c96985d9132fc6f05b2e0fa67048fd/src/Chunk.cpp#L629

And the targeting monster may execute this after the free:
https://github.com/cuberite/cuberite/blob/85e534b745c96985d9132fc6f05b2e0fa67048fd/src/Mobs/Monster.cpp#L239

Is my reasoning correct?
Slightly related forum thread: [safety of cMonster::m_Target](http://forum.mc-server.org/showthread.php?tid=2324&pid=24663#pid24663)

**Comment by LogicParrot** [comment]
Possible resolutions:
 - shared_ptr
 - Asking cWorld to not destroy entities immediately. Instead put them in a "graveyard" and destroy them after some time to give everyone the chance of safely seeing that isDestroyed is free and drop the pointer.

**Comment by madmaxoft** [comment]
Possible solution 3: Add a "notification" to each entity, so that it notifies its peers that it's being destroyed (the "riding" uses this approach). A bit inelegant, but solves the problem.

I'd very much like the idea of `SharedPtr` for all game objects, including sharing the pointer with Lua API-wise, so that we can finally store an object pointer in Lua code instead of going through the `DoWith` callbacks. However, this is difficult and would most likely break API compatibility. The `cNetwork` API tries to be that way and still fails in some corner cases ( #2604 ) and the code needs to decide, on a per-function level, what to do if the object is no longer "valid" - it exists but isn't active in the gameplay anymore (dead mobs, disconnected players etc.)

**Comment by LogicParrot** [comment]
Solution 3 would solve pworld traveling problems]((http://forum.mc-server.org/showthread.php?tid=2324&pid=24663#pid24663) - Just "lie" to all entities and tell them we're destroyed before teleporting.

**Comment by LogicParrot** [comment]
I tried solution 3 in #2939.
