### ISSUE TITLE
Leads do not work properly

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2915]
Part of this is already covered in issue #2729 but leads do not work at all.

When using a lead on horses you occasionally get on the horse.

When using a lead on an animal and then clicking on a fence gate the lead does not attach the animal to the gate.

As #2729 say animals do not follow you when using a lead.

Related to #2729 leads do not break after long distances.

**Comment by spekdrum** [comment]
Can anyone  assign this issue to me please? I'm working on it.

**Comment by madmaxoft** [comment]
Unfortunately you cannot be assigned to an issue unless you're a member of the Cuberite organization. But since you've shown real interest and committed good code already, I think we could add you. Anyone against, @cuberite/server ?

**Comment by Seadragon91** [comment]
Add him :)

**Comment by spekdrum** [comment]
eemmm ok, no problem! I've just ask for the assignment to avoid over efforts. Of course I will be pleased to be a part of this. Thanks for you compliment btw.

**Comment by madmaxoft** [comment]
Done.

**Comment by spekdrum** [comment]
Thanks!

**Comment by spekdrum** [comment]
Need some help here please. I added a new entity that extends HangingEntity: LeashKnot in order to put a knot on a fence when the player right-click on it. It seems that the new entity is working, because it shows on the client, but only if I comment out every line of code related with cPluginManager::Get()->CallHookX. If I don't disable those lines I get this assertion:

> Program: S:\git\cuberite\Server\lua51.dll
> File: S:\git\cuberite\lib\lua\src\lapi.c
> Line: 57
> Expression: idx != 0 && -idx <= L->top - L->base

I've put the new entity header "cLeashKnot.h" in the AllToLua.pkg file but I get the same error.

Anyone can give me some light about this assertion? How do I make the LUA stuff to meet the new entity?
Thanks!

**Comment by Seadragon91** [comment]
Caan you push the code in a branch?

**Comment by spekdrum** [comment]
Yep!
https://github.com/cuberite/cuberite/tree/leads-wip

**Comment by Seadragon91** [comment]
Okay what are you doing that you get that error?

**Comment by madmaxoft** [comment]
I believe this is because of the code pushing entities to Lua state - it needs to push the correct Lua type, so it does indeed inspect the EntityType. You added a new type that the code doesn't know and it has poor forward-compatibility (doesn't even assert in such a case), so things that used to push Lua entities suddenly silently fail, leaving the Lua short of one parameter.

You'll need to add the new entity type to the big switch in `void cLuaState::Push(cEntity * a_Entity)` (src/Bindings/LuaState.cpp:933).

**Comment by spekdrum** [comment]
Thanks @madmaxoft, will try that.
@Seadragon91 just right click on a fence.

**Comment by Seadragon91** [comment]
Well and I did that :) And got no error, hehe

**Comment by spekdrum** [comment]
Really? xD I didn't commented the code, in fact I tried again yesterday and crashes everytime. However I didn't try madmaxoft fix yet.

**Comment by spekdrum** [comment]
With madmaxoft's fix there are no more crashes, so I keep going.
I have this functionality pretty advanced. It involves a a bit more work than I imagined at first!
