### ISSUE TITLE
Minecarts don't accelerate properly on powered rails

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2946]
I've tested various tracks with powered rails, and the Minecart doesn't seem to use them at all. In fact, whenever it's supposed to accelerate, it slows down and usually stops completely, even when the rails are powered up.

**Comment by marvinkopf** [comment]
Accelerating works for me. Were the rails really activated? There seems
to be a bug that the rails don't activate when being placed next to a
power source.

**Comment by jammet** [comment]
I put a redstone torch right next to the rails to keep them activated at all times. It might be the power source problem then.

**Comment by rekuen** [comment]
I can confirm this, not in powered rails, but in regular ones, the cart doesn't accelerate when you push it or when you are in it unlike vanilla. Also when you place a torch next to a powered rail, and then destoy the rail and put a new one, this new one doesn't activate itself again. You need to remove and put the torch again in order to make it work as marvinkopf states in PR #2985.
