### ISSUE TITLE
We need the redstone BUD activation!

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [cuberite/cuberite#2965]
The BUD activation or indirect activation comes in place when  a powered block is diagonally above or two blocks above dispensers, droppers and pistons, wich then also activate. **That is observed in vanilla and has already been declared as a feature, but doesn't occur in cuberite servers.** Many advanced redstone contraptions are massively compacted by making use of the BUD, and I as a redstone addicted would really like to see this again on cuberite.

**Comment by NiLSPACE** [comment]
Could you put the source where it has been declared as a feature? I've always thought that it was a bug.

**Comment by InterplanetaryEngineer** [comment]
https://bugs.mojang.com/browse/MC-108
According to the moderator, Grum just intended this feature.

**Comment by tigerw** [comment]
Man, I was dreading the moment someone asked this to be ported back into the simulator.

I was testing piston behaviours during the rewrite and found this, thinking, wait what? And then, oh, it's one of the block update detectors ~~that's totally not a bug~~ isn't it, and then, oh God, how am I meant to put this in? I'm not Microsoft!

Will you be satisfied with a special block, say, gold, that pulsed with a block update? The current simulator isn't really designed with this concept in mind at all.

**Comment by tigerw** [comment]
I suspect though, that you'll be unwilling to modify large structures for use here. What sort of contraptions are these?

**Comment by SphinxC0re** [comment]
Note, that unlike Vanilla, there is no advantage performance wise here, using a BUD. The simulator doesn't take up that much performance

**Comment by LogicParrot** [comment]
Perhaps this is a sign that the simulator needs a yet another rewrite :package:

**Comment by SphinxC0re** [comment]
I don't really know. BUDs offer a clean wah of exploiting block updates for building farms. I believe it's mostly farms, so I don't really care

**Comment by Pokechu22** [comment]
It's important to remember: quasiconnectivity isn't useful for only BUDs; it's got other uses in redstone.

An example of where quasiconnectivity matters outside of BUDs would be the classic jeb_ door, which has redstone that powers 2 sets of pistons below it.  Or, the standard monostable circuit that has a repeater pointed to a piston facing vertically and connects a wire to the other side (though that may not work in cuberite for other reasons).

All of these things can be done without quasiconnectivity, although it can be harder (and existing designs use quasiconnectivity).

Basically, not supporting quasiconnectivity means that things that seem like they _should_ work will suddenly not work.  Even if gold blocks were made into BUDs (or even if the 1.11 observer was added) quasiconnectivity is still needed.

Also, quasiconnectivity is surprisingly well-defined, once you look at it.  Rather than pistons being just powered from the faces next to them except for their head, they also accept power from the block above them from all sides except for down (even if that block is air).  The only reason that this generates BUDing is that the piston doesn't "realize" that its state should have changed when the power on the upper block changes; the hard part of implementing quasiconnectivity is figuring out when the piston is allowed to realize that its state should have changed.

And then there's dropper/dispenser quasiconnectivity.  It's like piston quasiconnectivity except it's a lot less commonly used.  It might be worth implementing, but the rarity of its uses makes it less important.

**Comment by tigerw** [comment]
So it starts off alright, pistons accept power from the extra positions. Repeaters etc. need to send power to the new weird positions if there's a piston there.

The problem is that the simulator doesn't update blocks the same way that vanilla does. It only updates the bare minimum (i.e. levers update only immediate adjacents). I worry changing the behaviour might impact performance for large redstone builds due to unnecessary updating.

The alternative being many more BUDs than even vanilla has, but the insane mechanic will work either way.

**Comment by peterbell10** [comment]
If you reworked this, would it also fix #3676 and remove `cSolidBlockHandler`.

**Comment by tigerw** [comment]
Not without a specific focus, but I guess it could be done.

**Comment by peterbell10** [comment]
Also, going back to you're earlier idea:
>Will you be satisfied with a special block, say, gold, that pulsed with a block update? The current simulator isn't really designed with this concept in mind at all.

You could implement the [observer block](https://minecraft.gamepedia.com/Observer) as a stopgap solution.  Assuming that would be easier than quasi-connectivity, of course.

**Comment by tigerw** [comment]
Thanks Mojang :)

Also is that issue still valid? I can do both //hsphere and //sphere 50 on a Release build without issue.

**Comment by peterbell10** [comment]
IIRC, you can actually crash with out of memory if you add too many blocks to the redstone simulator.

**Comment by tigerw** [comment]
Well yeah, it's not entirely stateless.

**Comment by peterbell10** [comment]
Well, yes but it's only really because solid blocks need to be updated that its queue grows that large.  Not exactly a high priority issue though; you need to do something pretty crazy to trigger it.

**Comment by madmaxoft** [comment]
Is there any credible source that would describe minecraft redstone mechanics in such a great detail that it could be used for implementation? Ideally, something like "Block X interacts with redstone in the following 3 configurations: 1. If there's a redstone torch under it, it does BLA, 2. If there's a block of redstone above it, it does BLE, 3. If neither, it is inert to redstone..."
Because I'm quite lost in how redstone works lately, it used to be simple (enough), but it's been reworked so many times that it's this kind of unintuitive spaghetti monster from the players' point of view, as well as reimplementors'.

**Comment by tigerw** [comment]
Workaround in #4638
