### ISSUE TITLE
Snowballs can crit and do damage

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2970]
When jumping or flying snowballs will crit. This is correct behavior for bows, but snowballs should never do damage, and when they crit they do damage.

**Comment by Taredon** [comment]
This seems to be due to a general bug within crit damage calculation which is done [here](https://github.com/cuberite/cuberite/blob/master/src/Entities/Entity.cpp#L511). After looking up the damage section on [gamepedia](http://minecraft.gamepedia.com/Damage#Critical_hits) that says a crit is defined as 150% base damage, i think this could be easily fixed by replacing `a_TDI.FinalDamage += 2;` with `a_TDI.FinalDamage += (a_TDI.RawDamage*0.5);`. This however is based on my limited knowledge since im new here (a_TDI.RawDamage is the original damage of the actual attack to my understanding)
