### ISSUE TITLE
Investigate addition of entities to invalid chunks

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3045]
#3044 deals with #3042 and #3035 deals with #3030, however, both are quick fixes, and we should check if there are more fundamental problems with dealing with entities going into invalid chunks, and there probably are such problems.

**Comment by tigerw** [comment]
Normally such entities are simply lost.
 
Date: Mon, 22 Feb 2016 00:43:10 -0800

**Comment by madmaxoft** [comment]
This is a scenario that should be completely avoided. Entities shouldn't ever be moved to an unloaded chunk.

My initial idea on how to solve this was to introduce a `m_HasAllNeighbors` flag for each chunk that would be true if all 8 neighbors of this chunk were valid; and all entities in such a chunk would be ticked only if the flag is true. This would mean that entities on loaded world's border won't be ticked, which seems like a good idea to me - minecarts would stop moving when they reach the edge of the world, rather than when leaving the loaded world completely etc.

Just haven't got around to actually implementing this yet, and I don't currently know how it would work with the ParentChunk rewrite.

**Comment by LO1ZB** [comment]
Please do not forget, that some (block) entities are capable of loading/generation chunks without a player near by, like PrimedTnT and Minecarts in vanilla Minecraft. I dont have time to search for a list, will do that later today.

**Comment by Schwertspize** [comment]
Do we really want that tnt minecarts generate a new chunk? (obviously that seems strange because they can't be on the track any longer. Maybe anotherr possibility instead of just not ticking would be ticking them 100 times slower.

A way better thing would be if we handle unloaded or invalid chunks like world border in Vanilla. It's basically a border between blocks which are handled LIKE solid blocks or something I think

**Comment by NiLSPACE** [comment]
If an entity other than a player goes out of the loaded chunk can't we:
* load or generate the chunk 
* save the entity in the newly loaded chunk
* unload the chunk
?

I believe Vanilla does that as well.
