### ISSUE TITLE
Remove Android folder

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#3064]
Now that the new Android app is being made (https://github.com/cuberite/android), I suppose we can remove the Android folder in this repository?

**Comment by Schwertspize** [comment]
I think so. The Android folder was basically the attempt to use jni and the NDK. Should I create a pull request?

**Comment by tigerw** [comment]
I still think the NDK is the better way, and #2562

**Comment by madmaxoft** [comment]
I say we shouldn't get rid of the folder until there's a working Android compilation in that repo, together with a guide that at least one other person verifies works for them.

**Comment by Schwertspize** [comment]
@tigerw Maybe a bit wrong here, but could you elaborate on why exactly you think the NDK is the better way?

@madmaxoft True.... But 1. I didn't get it to run with the Android directory in the main repo, 2. The Android repo isn't meant to be compiled yourself. It doesn't compile cuberite, too (I mean user experience..... Wanna tell the user that he has to download half a gig and then wait 5 minutes to compile that thing before it works? Dev tools just doesn't make sense on an android device)

**Comment by tigerw** [comment]
One has to defend what one makes; not like anyone else will, especially with this group of disinterested programmers :P

I just want to clarify what your method can and can't do - the NDK has gotta exist for some reason right?

1. Is it compatible with phones that have software floating point?
2. Android 2.3.6?
3. Reproducibly run without root (tested on ideally non-rooted phones)?
4. Not require some terminal emulator to be installed?
5. Not dump binaries where binaries are not meant to go?
6. Conform to the Play Store's guidelines?

**Comment by Schwertspize** [comment]
1. Right, it may not be supported. 
2. Google advises to use api 15, because it's something between features and reaching over 99% of the users
3. Yep. (not tested on non-rooted phones BUT if I don't run it explicitly as root (and deny root for that app) with /system/xbin/su it is not using root
4. Doesn't need a terminal emulator. Only now root and shell are needed for installation because I'm not yet finished
5. There are no place where binaries are meant to go, I place them in the so called internal storage which is not reachable for the user
6. Yep

Additional: 
7. No need to download stuff like libraries or server dir like every time an update comes
8. Every build has to increase the version number 
9. No publishing api to play store
10. Play store delay, and you get "updates" when you don't use the app actively and don't get the when you want to use it (delay) 
11. Far less programming afford. 
12. Way better to debug if something is wrong (we can differ directly between app and cuberite, with cuberite we get the normal core dump etc and we can even implement to publish the core dump with one click)

**Comment by tigerw** [comment]
7. Updating is by definition downloading stuff like libraries, right?
8. That's the only way to update without subverting the Play Store mechanisms.
9. Parse failure (don't quite understand) :P
10. Again, only way to update. Probably lock it at once per week.
11. Well, that's entirely debatable. Both systems just need to be compiled when finished.
12. That's also entirely debatable. I doubt the NDK method will somehow prevent coredumps from being created/published.

Additional pros for NDK:

1. Everything's placed into one APK, which goes into its "proper" folder somewhere in /data. No downloading of binaries from a buildserver, etc.
2. And so will clean up fully when uninstalled. Please correct me if your binaries are also placed in a folder that is removed by the uninstall manager.
3. For those who want to compile it for themselves, it *doesn't* require a Raspberry Pi, i.e., compilable on Windows, x86, etc.
4. Doesn't introduce a dependency on the RasPi builds; so if something changes about them in the future, it won't break Android.

To be perfectly honest, all this is going to be really niche anyway. I doubt the general populace will find great utility in having their phone run a server which will pretty much stop when they leave the screen.

**Comment by bearbin** [comment]
If we want to distribute through the play store (which we do) we need to use the NDK. Any other options are secondary, if they have significant enough benefits to warrant additional development then they can be used alongside the NDK method.

**Comment by Schwertspize** [comment]
Sorry for my wall of text :stuck_out_tongue: :) 

1. Correction, the only thing not Uninstalled is the Server directory but I think there is a flag for even in installing that, we can discuss that. Binaries, libraries are removed (they ARE actually in the /data directory. 
2. Correction @bearbin we don't have to. May I quote [stackexchange](http://stackoverflow.com/a/27144612/5196732)? 

>You have 2 options:
>
>1) Call library functions via a wrapper: a class that defined a set of native functions. You will have to convert data structures between the Java representation and the C representation. A Java object maps to a very specific kind of C data structure, and C structures cannot be normally accessed from Java. So for each invoked C/C++ function there is a wrapper that implements a Java native function.
>
>2) You can invoke a shell command. Android is Linux, and you can communicate to it via adb shell. You can pass command-line arguments, write/read to/from stdin/stdout of the started process. You also can pass data to/from the started process via the file system. 

(you don't even need adb shell, and btw seems like much more afford for me if you use the NDK)

NDKs pros are pretty much if you either depend on direct interaction between java and c++ code (with that, we maybe discuss java plugins again [nononono, just fun]) or your code doesn't change independent to the app. Basically when using the NDK, we tie app and cuberite together (no independence, etc). Do we want this? (IMO no) 

Another note: our keystore would have to be on a build server (notice that) with either a hard-coded password or no password. This is definitely not good. And as I already said, android isn't made to compile your stuff yourself. (additional note: compiling cuberite on your own would me easier without the NDK, because you don't need javac, you don't need the NDK and so on, you need a cross compiler (most likely, or a raspi). And then you simply have to put the binary on your phone like you do it with your music and press a button in the app (this is rather easy to implement, the app would just ask the user for the cuberite executable and then include it into its internal storage with another name).

Another one: in fact I have seen many apps which downloads additional stuff in app from their respective servers... Especially if this is about the latest 10mb update, this isn't a problem. Also, bug fixing would be pretty bad if you always know that what you are running on the phone is outdated.

And btw why not subvert play store? Play store is designed to ship applications and apks, not such binaries as we have them (these are "nightlies" right? (I mean on every push compiled) 

And additionally, it would be much easier to switch between what we are running because you can (if we once have that) switch between a testing or stable branch or normal/debug builds and afterwards download what's necessary (dialog....) now we don't have a testing branch, we got a ingame-testing-nedded tag :). Not like providing 5 apps where you don't know which ones they are, have maybe multiple copies of the same stuff (or even not the same world/config) or pack all available options into the apk (note, debug builds are uncompressed around 80mb as I counted it last time I think [maybe 70,but still, 10 times more than normal builds]) 


He'll, why do I have to defend what I am doing :stuck_out_tongue: 

And btw who tells about stopping the server onPause().... We are going to do it like every other app.... Notification and the background task (notification both to indicate that it's running and to prevent android from killing it)

**Comment by mathias-github** [comment]
Closing this for now, since work has been made on the Android app in this repository.
