### ISSUE TITLE
APIDesc.lua automation

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3131]
Think we can automate the generation of `APIDesc.lua` via the source code doxy comments? This would require a single time convertion of `APIDesc.lua` to source code comments.

@madmaxoft

**Comment by bibo38** [comment]
Would be nice :+1: . Makes the documentation of the code easier.

**Comment by madmaxoft** [comment]
#3204 generates description files that include the doxycomments.
I'll code a script to merge this into the APIDesc.lua file, I expect this to be a one-time action; I won't bother with a permanent solution though.

The reason for that is that I'd like to reverse the way bindings are generated. Instead of parsing C++ code and generating C++ bindings code and Lua descriptions out of it, I'd like to have a Lua API description file from which both the full documentation and the bindings code would get generated. No more parsing C++ code from Lua.

**Comment by madmaxoft** [comment]
I'm closing this now, the `src/Bindings/DiffAPIDesc.lua` script does diffs between the documentation read by automatic bindings generation and APIDesc; these are not added to APIDesc.lua automatically since it could cause loss of comments / formatting inside that file.
