### ISSUE TITLE
Leaving the minecart kills you if there is no space to place the player.(survival)

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#3147]
I think  this issue has been recently introduced by some PR, because it has never behaved this way before.

### Expected behavior
If you step out of a minecart and you don't have enough space around you to leave the minecart, it shouldn't let you leave the minecart.

### Actual behavior
When you leave the minecart and the space around is not enough to place the player the game tries to place it in the first block available, on one or the other side of the minecart, and if you are too far underground it literally kills you, otherwise it hurts the player.

### Steps to reproduce the behavior
Dig a hole undergroud (make sure you have plenty blocks above you), make a  tunnel of 2 or 3 blocks tall (just enough to fit the player and whatever longitude you like, place the cart and in the middle of the tunnel just leave the cart.

**Comment by Pokechu22** [comment]
The Notchian server tries to put you outside of the minecart but falls back to putting you on the same tile as the minecart (even if that tile is obstructed).  However, it isn't correct behavior to put the player to the side of the minecart inside of a block.

How do I know?  I actually _wrote_ the code that's used to decide where to get out of minecarts - see [MC-52274](https://bugs.mojang.com/browse/MC-52274).  Here's the new logic:

```java

/**
 * Moves the entity to a position out of the way of its mount.
 */
public void dismountEntity(Entity dismountedFrom)
{
    double dismountedX = dismountedFrom.posX;
    double dismountedY = dismountedFrom.getEntityBoundingBox().minY + (double)dismountedFrom.height;
    double dismountedZ = dismountedFrom.posZ;
    byte testRange = 1;

    for (int offsetX = -testRange; offsetX <= testRange; ++offsetX)
    {
        for (int offsetZ = -testRange; offsetZ <= testRange; ++offsetZ) //Changed < to <=
        {
            if (offsetX != 0 || offsetZ != 0)
            {
                double x = (this.posX + offsetX); //Changed int to double and removed cast
                double z = (this.posZ + offsetZ); //Changed int to double and removed cast
                AxisAlignedBB aabb = this.getEntityBoundingBox().offset((double)offsetX, 1.0D, (double)offsetZ);

                if (this.worldObj.func_147461_a(aabb).isEmpty())
                {
                    if (World.doesBlockHaveSolidTopSurface(this.worldObj, new BlockPos(x, this.posY, z))) //Removed posY cast
                    {
                        this.setPositionAndUpdate(this.posX + (double)offsetX, this.posY + 1.0D, this.posZ + (double)offsetZ);
                        return;
                    }

                    if (World.doesBlockHaveSolidTopSurface(this.worldObj, new BlockPos(x, this.posY - 1, z)) || this.worldObj.getBlockState(new BlockPos(x, this.posY - 1, z)).getBlock().getMaterial() == Material.water) //Removed posY casts
                    {
                        dismountedX = this.posX + (double)offsetX;
                        dismountedY = this.posY + 1.0D;
                        dismountedZ = this.posZ + (double)offsetZ;
                    }
                }
            }
        }
    }

    this.setPositionAndUpdate(dismountedX, dismountedY, dismountedZ);
}
```

In all cases, it'll let you out of the minecart, but it should still try to find a good position.

Here's cuberite's logic (which is similar but also different), from `cPlayer::Detach` (line 2436):

```c++
void cPlayer::Detach()
{
    super::Detach();
    int PosX = POSX_TOINT;
    int PosY = POSY_TOINT;
    int PosZ = POSZ_TOINT;

    // Search for a position within an area to teleport player after detachment
    // Position must be solid land, and occupied by a nonsolid block
    // If nothing found, player remains where they are
    for (int x = PosX - 2; x <= (PosX + 2); ++x)
    {
        for (int y = PosY; y <= (PosY + 3); ++y)
        {
            for (int z = PosZ - 2; z <= (PosZ + 2); ++z)
            {
                if (!cBlockInfo::IsSolid(m_World->GetBlock(x, y, z)) && cBlockInfo::IsSolid(m_World->GetBlock(x, y - 1, z)))
                {
                    TeleportToCoords(x, y, z);
                    return;
                }
            }
        }
    }
}
```

Cuberite cares about a solid block below and an air space above, which still allows getting stuck.  The notchian server does a full bounding box check, and also does either a solid block or (with boats) solid or water one block below.

**Comment by rekuen** [comment]
I can see how it works, but it makes no sense that if there's no space my player get teleported 20 or 30 blocks up from the position where it was and get killed because of that, I'd rather see more fit to not let the player detach if let's say the destination space is X blocks away from the original position.

That X been a small number, I can make a video if you want to see how the player gets teleported from the underground mine to overground and gets killed.

Or I can make my rails tunnels one block wider, anyway it feels like a bug to me.

**Comment by Pokechu22** [comment]
> I can see how it works, but it makes no sense that if there's no space my player get teleported 20 or 30 blocks up from the position where it was and get killed because of that, I'd rather see more fit to not let the player detach if let's say the destination space is X blocks away from the original position.

Wait, what?  That shouldn't happen at all (either with the Notchain code or the cuberite code).  That behavior doesn't make sense.  A video would be nice.

I think players should always be able to detach, but it shouldn't move them more than a block or so away from their original position (the notchian code only lets y vary by 1 block; cuberite's code looks like it gives 4 blocks).

**Comment by rekuen** [comment]
Here is the video:
https://youtu.be/ANOfCgvNh3k

As you can see I'm on floor 11 on Y axis, and it teleports me to level 63 and it gets killed.

**Comment by Pokechu22** [comment]
That definitely is a bug.  It should drop you on the rail at your current Y value, not teleport you that far up and kill you.

Perhaps it's because of the single-block air spaces next to you rails.  However, I'm not sure exactly why that would teleport you to Y=63 (if you got stuck in the wall, maybe, but going to the surface makes no sense).

I'll look into this (and also probably redo dismount code to use the "correct" code).

**Comment by LogicParrot** [comment]
I can see why it teleports to the surface. Minecart calls `detach`, `detach` calls `teleportToCords`, `teleportToCords` never teleports players to solids, instead putting them up on the place with sufficient space in that column, in this case, it was the surface.

`cPlayer::detach` needs rewriting. Should be simple.

**Comment by tigerw** [comment]
TeleportToCoords does that?

\~~~

"Plugin authors hate it!"

**Comment by Pokechu22** [comment]
It'll be a bit more complicated to rewrite it (since technically, _all_ entities should use that "nearest open space" dismount logic, and then you have to deal with hitboxes) but for a player it's not _too_ complicated.

Also, seriously, `TeleportToCoords` does that?  It doesn't _look_ like it does, at least there isn't a loop that would do it.

```c++
void cPlayer::TeleportToCoords(double a_PosX, double a_PosY, double a_PosZ)
{
    //  ask plugins to allow teleport to the new position.
    if (!cRoot::Get()->GetPluginManager()->CallHookEntityTeleport(*this, m_LastPosition, Vector3d(a_PosX, a_PosY, a_PosZ)))
    {
        SetPosition(a_PosX, a_PosY, a_PosZ);
        FreezeInternal(GetPosition(), false);
        m_LastGroundHeight = static_cast<float>(a_PosY);
        m_bIsTeleporting = true;

        m_World->BroadcastTeleportEntity(*this, GetClientHandle());
        m_ClientHandle->SendPlayerMoveLook();
    }
}
```

It looks like `TeleportToCoords` also is supposed to reset fall damage.

That said, it does seem like a bug in `TeleportToCoords` is the most likely cause.

**Comment by LogicParrot** [comment]
`TeleportToCoords` does that, and this was a recent change by me. Well, specifically, the unfreeze code does that, but `TeleportToCoords` triggers it via `FreezeInternal(GetPosition(), false);`

I wouldn't consider it a bug, It was a recent feature introduced by me; I thought it's wrong for players to ever teleport into solids and get stuck inside, whether by using `/portal` or `/tp`. Wouldn't it be more proper to make  `detach` not teleport into a solid rather than modifying `TeleportToCoords`?

**Comment by tigerw** [comment]
"Escape death with this one weird trick. Plugin authors hate it!"

**Comment by LogicParrot** [comment]
@tigerw I don't understand.
If one has access to the tp command, once can escape choke death anyways.

**Comment by Pokechu22** [comment]
IMO, that doesn't feel like logical behavior for `TeleportToCoords` (since that method just doesn't feel like one that would adjust coordinates and there is nothing in it that makes it look like it should).  In any case, the changed behavior for it does seem to be causing issues, specifically the fall damage (with the fall height not getting set to the new position?).

Perhaps that behavior should be something like "TeleportToCoordsSafe".  I can see the benefit command-wise of going to a different, "safer" position, but it shouldn't be the _only_ way to teleport.

Detach shouldn't go inside of walls, yes.  Right now it's doing that because it only checks for a single block of air space rather than 2 (which you can see in rekuen's video).  Rewriting it to use the correct algorithm would mostly fix it.

However, if one is in a rail line with no air space above the minecart (and thus are _already_ suffocating), they shouldn't be teleported to the surface when they get out of the minecart.  That produces the same kind of thing as a "waffle lift" from very old versions (if anyone remembers those, let me know).  The behavior there is to just get them out at the minecart, no teleportation, and let them deal with the fact that they are already suffocating anyways.

**Comment by tigerw** [comment]
> @tigerw I don't understand.
> If one has access to the tp command, once can escape choke death anyways.

Well, a plugin could try to teleport a player into a block, hoping that they'd suffocate. But aha! TeleportToCoords saves the player! (perhaps not, and something else is just broken between Detach and Teleport, I don't know, it's a joke.)

And because of the "get rid of belly fat with this one weird trick/doctors hate it!" advertisements: excellent candidate of humour!

**Comment by LogicParrot** [comment]
Okay. I think it's best if I add a `safe` flag for `TeleportToCoords`:
`cPlayer::TeleportToCoords(int posx, int posy, int posz, safeTeleport = false);`

Objections?

**Comment by LogicParrot** [comment]
Instant death can also happpen with the `/portal` command, apparently for identical reasons. The `unfreeze` code needs change as well.
