### ISSUE TITLE
Can't restart cuberite via webinterface or command

### ISSUE THREAD

**Issue by nolantern** [cuberite/cuberite#3177]
### Expected behavior

Cuberite restarts when pushing the "Restart Server" button in Webinterface.
Restart meaning Cuberite shuts down and then starts automaticly.
Cuberite restarts when typing `restart`in commandline.
### Actual behavior

When i push the "Restart Server " button, Cuberite shuts down. Now it doesn't start automaticly.
I'm running Cuberite on Bananian/ Lemaker Banana Pro.
Cuberite started by typing `./Cuberite` using a Screen session via SSH.
I tested it with and without `sudo`.

Edit: now I tested typing `restart` in commandline and its the same thing. Cuberite shuts down and don't starts.
### Steps to reproduce the behavior

Pushing the "Restart Server" button in Webinterface.
Edit: or type `restart` in commandline.

**Comment by mathwhiz1212** [comment]
Same issue here.

**Comment by popinskii** [comment]
you can use this command and terminal will not shut down!!!! and server will reboot 
       
while :; do ./Cuberite; if [ $? -eq 0 ]; then break; fi done

**Comment by Schwertspize** [comment]
You should note that at least for me I get the message that it would hang and cause of that shutdown

**Comment by PureTryOut** [comment]
Reproducable here on latest build (ec998e8 right now). Happens both in the webinterface but also when typing `restart` in the terminal.

**Comment by madmaxoft** [comment]
This problem doesn't happen for me. I click the "Stop server" button in WebAdmin and the server stops.

Perhaps this is OS-specific. I'm using Windows, maybe it's a problem with Linux only?

**Comment by Seadragon91** [comment]
Yes the restart command doesn't work under linux.

**Comment by PureTryOut** [comment]
It's broken on all platforms it seems. For me it's broken on both Linux and FreeBSD.

**Comment by 0x4368697473756B6F** [comment]
the restart doesn't work on my OS X 10.11 too.

**Comment by PureTryOut** [comment]
@madmaxoft note that stopping the server works fine, it's restarting that doesn't work. As in, it stops fine, but then doesn't launch itself again.

**Comment by madmaxoft** [comment]
I confirm that restarting works on Windows, but doesn't on Linux - instead of a restart, the server terminates completely.

**Comment by tigerw** [comment]
I see. pthread_kill (the input thread) always returns != 0 so the server sets the shutdown flag.

**Comment by madmaxoft** [comment]
This will require a major overhaul of how the server works.

Currently, the Input thread accepts input from the console and sends it as commands to `cRoot`. However, it is impossible to terminate the thread reasonably, because it executes a blocking read on `std::cin`. On Windows, we currently overcome this by simulating a keypress in the console; I couldn't find any similar API for this in Linux.

A better architecture would be to split the entire Cuberite server into kind of a library, with a single well-defined API point - the `cRoot` object, and with entrypoints for incoming console commands and callbacks for console output / lifetime management. Then, a wrapper application that parses the cmdline parameters, fills in some settings object, spins off an input thread and creates a new `cRoot` instance. Then, restarting means re-creating a new `cRoot` instance, but not killing the input thread.
