### ISSUE TITLE
Minecraft 1.9: Sound problems

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3189]
### Expected behavior

Built a ding dong doorbell with pressure plate to hear noise when someone enters.
Killing blows to mobs makes noise.
Opening chests makes noise.
### Actual behavior

Makes no sound. Or even makes the _wrong_ sound.

**Comment by jammet** [comment]
It's not just missing sounds - some of them have the wrong sounds.

**Comment by mathias-github** [comment]
Yes, the sound names and effect IDs changed in Minecraft 1.9, which is why sounds and effects are wrong. They were not changed in Cuberite yet.

**Comment by mathias-github** [comment]
Is it worth adding new code that handles both 1.8 and 1.9 sounds at this point, when 1.8 is barely relevant right now? I think we could just update the sound names and effect IDs to the 1.9 ones, if it doesn't cause large issues for 1.8 clients. After all, I don't think Mojang will update the sound names in a while after 1.9.

**Comment by jammet** [comment]
I'm all for it. And while at it, would it not be nice if the missing sounds
were implemented? Mobs are mostly mute.

**Comment by Pokechu22** [comment]
I feel that the risk that these effect IDs will be changed is small, but large enough that having code to handle it for both versions would be a good idea.  (But if that seems like it would be too much work for too little reward, then just doing 1.9 events and dropping them for 1.8 would also work).

As for sounds:  The textual sound IDs didn't change at all between the versions, and I doubt they will in the future.  But _numeric_ sound IDs have changed in nearly every version, even between minor releases (albeit ones with different protocol IDs), such as 1.9 to 1.9.2.  So the best plan is to just stick with textual sound IDs which are supported both in 1.8 and 1.9 (and are used for `/playsound` in vanilla so it's not like that packet's gonna disappear).

**Comment by Pokechu22** [comment]
In fact, you can even safely send a play sound packet with a textual ID to versions where the client doesn't have that sound, in which case the client won't play the sound.  So if adding new sounds then you don't have to worry about not sending them to older versions.

**Comment by jammet** [comment]
Sounds good. Literally.

**Comment by tigerw** [comment]
I'd even argue that focus should be placed solely on 1.10 (what a strange version) considering that there just aren't enough resources to maintain two versions properly, let alone three.

**Comment by LogicParrot** [comment]
#3201

**Comment by Pokechu22** [comment]
Adding on to this: What I said about sound IDs seems to be actually somewhat incorrect.  While the textual sound IDs generally don't change between versions, they still _did_ change between 1.8 and 1.9 when they added the numeric sound ID packet.  That's why most sounds don't currently work.  But I don't think they'll change them again between versions.

Looking at [the transforms ViaVersion performs](https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/sounds/SoundEffect.java) should show the change in IDs pretty clearly.  ([There's also one for the effect packet](https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/sounds/Effect.java)).  There aren't any transforms that are performed on textual sounds between 1.9 and 1.10.

If 1.8 support were dropped, then it would be pretty easy to just change all the sound effect IDs to the 1.9 ones.  Or alternatively, we can switch to the 1.9 IDs without dropping 1.8 - then 1.8 won't have sounds, but at least we'll have sounds in 1.9.

Easiest way to

**Comment by mathiascode** [comment]
The sound names have been updated to 1.9 and above.
