### ISSUE TITLE
Blocks can be placed inside yourself

### ISSUE THREAD

**Issue by pfgithub** [cuberite/cuberite#3196]
Client version:   1.9.4
Commit id:        f73de02684ce2c5f9fb2e8e36cfe65dc4ac91dea
### Expected behavior

When you right click below you holding a solid block, nothing will happen
### Actual behavior

When you right click below you holding a solid block, a block will be placed, causing you to be pushed out of the way
### Steps to reproduce the behavior

Hold a solid block, face down, and right click

**Comment by mathias-github** [comment]
This happens in 1.9 only.

**Comment by LogicParrot** [comment]
"1.9 features :P " @sphinxc0re

**Comment by loibi93** [comment]
This issue was also present for me using a 1.11 Client. I fixed it with a little patch:
In the file /cuberite/Server/Plugins/Core/onbreakplaceblock.lua in function OnPlayerPlacingBlock after the check for core.build permission, i added:

`if (((BlockX <= Player:GetPosX()) and (Player:GetPosX() < (BlockX + 1))) and
	((BlockZ <= Player:GetPosZ()) and (Player:GetPosZ() < (BlockZ + 1))) and
	(((BlockY + 1) > Player:GetPosY()) and ((Player:GetPosY() + 2) > BlockY))) then
	return true	-- placed block inside yourself
end`
