### ISSUE TITLE
Deadlock when running heavy calculations in plugin

### ISSUE THREAD

**Issue by Cl1608Ho** [cuberite/cuberite#3322]
Client version:   1..8.8
Server OS:        Ubuntu 15.10
Commit id:        Latest, I do not have the right id because of several merges ([12:22:39] from commit id: approx: 3a3601fc840856ddd55b28336ae4e748480cf6f3 built at: approx: 2016-08-15 12:00:30 +0200)

### Expected behavior
No deadlock and no crashes

### Actual behavior
[12:22:39] Deadlock detected, aborting the server

### Steps to reproduce the behavior
https://github.com/Cl1608Ho/CuberiteMaze
activate my plugin and generate a larger maze, for instance, /maze generate 300 anything 
Note that anything in above can be any string, must be present but isnt used (logic for that is still missing, sorry)

**Comment by NiLSPACE** [comment]
The reason for this is while a plugin is executing it locks the server, so if the plugin is really busy the server thinks it's deadlocked. If you want you can disable the deadlock detector. Go to your `settings.ini` And under `DeadlockDetect` set `Enabled` to 0.

**Comment by Seadragon91** [comment]
If a plugin runs code and it rakes longer than 20 seconds, then the server aborts with an deadlock message. There is currently no way to run code in a asynchronous way.

I have also created a [MazeGenerator](https://github.com/Seadragon91/MazeGenerator) plugin.

**Comment by Cl1608Ho** [comment]
ok. still i think there should be a way that plugins can tell the server that they are doing hard work (tough calculations) while they are not using server ressources so they can either get their own thread or have no lock.

**Comment by NiLSPACE** [comment]
@madmaxoft is one step closer to [multi-threading for plugins](https://github.com/cuberite/cuberite/issues/2071) with PR #3311 (though it's still far far away).

**Comment by NiLSPACE** [comment]
Perhaps you can use [coroutines](https://www.lua.org/pil/9.1.html) for this. Execute for 50 miliseconds and then yield until the next tick.

**Comment by Cl1608Ho** [comment]
ok! as i understood it, i should yield every few steps in the for loop, but where do i have to place the resume code? in onTick()?

Thank you

**Comment by madmaxoft** [comment]
OnTick() hook would be the most appropriate place.

Do you think it's worth changing the `cDeadlockDetector` message to include the info about plugins possibly taking too much CPU?

The problem with locking is that Lua code needs to be accessed by only one thread at a time. Therefore there's a mutex that synchronizes access to each plugin's Lua engine. There's just no way to run "unlocked".

It could be done to actually run multiple Lua engines per plugin (that's what 3311 is a small part of), but there's still a question about how to initialize them, how to do inter-engine communication - if you create a new "thread", how will you give it code to run? You can't pass a function, because a function is bound to a specific engine and cannot be copied.
Lua actually has some limited support for running several threads in a single engine, but that imposes quite a lot of performance loss due to excessive locking (on the order of 100k mutex locks per second).

**Comment by NiLSPACE** [comment]
Yes, you save the coroutine somewhere globally in a table, and then on an OnTick you do something like this:
```lua
function OnTick()
	for key, coroutine in pairs(g_AllCoroutines) do
		coroutine.resume()
		if (coroutine:status() ~= 'suspended') then
			-- The coroutine has finished running. Paste the maze in the world and remove the coroutine from g_AllCoroutines
	end
end
```

The function with heavy calculations would look something like this: 
```lua
function heavyCalculation()
	local targetTime = os.clock() + 50 -- target time is 50 ms
	for --[[something]] do
		-- heavy calculation
		if (os.clock() > targetTime) then
			coroutine.yield()
			targetTime = os.clock() + 50
		end
	end
end
```

You might also be able to use something like this: https://github.com/cuberite/WorldEdit/blob/master/Classes/CraftScripts.lua#L113-L119

That code aborts a craftscript in WorldEdit if it's taking too long. Instead of aborting it you might also be able to yield the coroutine.

**Comment by madmaxoft** [comment]
Using `os.clock()` is not too smart, it is not consistent across platforms and on some platforms only gives a resolution of integral seconds.

Guessing a right size to slice the heavy calculation (such as N loop iterations) seems an easier and workable solution here.

**Comment by NiLSPACE** [comment]
@madmaxoft Could we initialize a thread with a subfolder in the plugin's folder? Then we could possible invoke functions that were declared globally.
```lua
local thead = cThread("Plugins/WorldEdit/ShapeGeneratingThread") -- All the files together represent a thread. In here there is a function called 'GenerateCylinder'
thread:CallFunction(
   "GenerateCylinder", 
   function(area) --[[Paste the area in the world]] end, -- OnFunctionFinish callback
   args
)
A little similar to how inter-plugin calling works.

**Comment by NiLSPACE** [comment]
It is? Then my WorldEdit plugin might not work properly. What should I use instead?

**Comment by madmaxoft** [comment]
I don't think there's anything better in the API. As long as the plugin is executing, the world's time doesn't increment, and that's about all the timing methods I can think of.

A thread from a subfolder could work, but what if you wanted to dynamically construct the code, rather than read it from files? I suppose the `cThread` constructor could be made to accept both. However, it doesn't solve one of our greatest pains, and that is webadmin vs world tick thread - if the webadmin handlers were executed in a separate thread, they wouldn't deadlock the server when accessing cWorld data. With your `cThread`, I can't see a way of doing this.

**Comment by madmaxoft** [comment]
The thread discussion is getting off-topic, we should move to the forum.

**Comment by Seadragon91** [comment]
Whats about a function exported to lua that returns the current time in milliseconds, instead of `os.clock`?

**Comment by Cl1608Ho** [comment]
@Seadragon91 actually, this already exists

GLOBALS:GetTime() or just GetTime().... in seconds unfortunatly (although unix time stams are normally in milliseconds)
