### ISSUE TITLE
Terrain generator made a 2x2 three with no dirt at half of the bottom

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3455]
Client version:   1.9.4
Server OS:        Linux (debian jessie)
Commit id:        ded59e9519c429c511866609d0e5e909f8e10aad

![screen shot 2016-11-22 at 13 21 08](https://cloud.githubusercontent.com/assets/4412002/20529454/5b4ed9b8-b0b7-11e6-954c-667cfc6c3e27.png)

**Comment by NiLSPACE** [comment]
This is pretty easy to fix. [This](https://github.com/cuberite/cuberite/blob/master/src/Generating/Trees.cpp#L597-L603) creates the trunk. What we need extra is a loop that goes downwards and places dirt until it reaches something solid.

All trees that are wider than 1x1 have this problem.

**Comment by yangm97** [comment]
![screen shot 2016-11-22 at 13 40 43](https://cloud.githubusercontent.com/assets/4412002/20530063/6868029e-b0b9-11e6-9d1a-22d22a657be7.png)
![screen shot 2016-11-22 at 13 40 31](https://cloud.githubusercontent.com/assets/4412002/20530065/6898eb20-b0b9-11e6-9cf7-86adc452cc9a.png)

Wouldn't something like this eventually happen if this loop gets added? Should't the code check if there's enough dirty before creating the tree instead?

**Comment by NiLSPACE** [comment]
I believe vanilla simply adds dirt below the tree instead of checking if there is enough dirt below it.

@madmaxoft We can't check for the dirt right? Since we have to think about the chunk borders.

**Comment by NiLSPACE** [comment]
Are those pictures from modified code, or is that another bug?

**Comment by madmaxoft** [comment]
The code can't check for "enough dirt", because the tree might be on a chunk boundary and the final dirt shape is not available (for example if a water lake cuts away the terrain).

I believe what @NiLSPACE proposed would be the best we could do in this situation; perhaps adding a "maximum number of dirt blocks added" - not adding more than 4 blocks, so the tree will be on a kind of an overhang.

**Comment by yangm97** [comment]
> Are those pictures from modified code, or is that another bug?

Neither, I just made this as an example.

**Comment by Balajanovski** [comment]
Hello,
If no one is working on the issue yet I would be happy to try solve it.

**Comment by Balajanovski** [comment]
Hey guys, it would be helpful if someone could tell me where the `sSetBlock()` method is located.

**Comment by NiLSPACE** [comment]
`sSetBlock` is a struct, not a method.
Something like this would suffice:
```cpp
for (int i = 0; i > -5; i--) 
{
	a_OtherBlocks.push_back(sSetBlock(a_BlockX, a_BlockY + i, a_BlockZ, E_BLOCK_DIRT, E_META_DIRT_NORMAL));
	a_OtherBlocks.push_back(sSetBlock(a_BlockX + 1, a_BlockY + i, a_BlockZ, E_BLOCK_DIRT, E_META_DIRT_NORMAL));
	a_OtherBlocks.push_back(sSetBlock(a_BlockX, a_BlockY + i, a_BlockZ + 1, E_BLOCK_DIRT, E_META_DIRT_NORMAL));
	a_OtherBlocks.push_back(sSetBlock(a_BlockX + 1, a_BlockY + i, a_BlockZ + 1, E_BLOCK_DIRT, E_META_DIRT_NORMAL));
}
```

**Comment by Balajanovski** [comment]
@NiLSPACE It has already been solved, I am just fixing some kinks so people who make custom terrain gen plugins won't have trees replacing bedrock at the bottom of the world. It is extremely difficult to test this sort of stuff due to how uncommon dark oak forests are, is there a tool I could use to better test terrain gen?

**Comment by madmaxoft** [comment]
@NiLSPACE That approach will create a dirt column if there is a cave under the tree. Not sure if that's what we want; on the other hand, it is by far the simplest approach.

@Balajanovski You can set your biome generator to constant, for example, then you'll have a fixed biome all through your world for testing.

**Comment by Balajanovski** [comment]
@madmaxoft @NiLSPACE Thank you for the advice, the edit has been committed.
I have tested the code and it solves the problem.

**Comment by Balajanovski** [comment]
@madmaxoft @NiLSPACE I was wondering if there is a method to retrieve a block's ID at certain co-ordinates.

**Comment by NiLSPACE** [comment]
No, I'm afraid not. That's because trees can overlap over multiple chunks, and if one hasn't generated yet you'd have to wait for that chunk to generate.

**Comment by Balajanovski** [comment]
@NiLSPACE How long is it going to take for my commit to be reviewed

**Comment by NiLSPACE** [comment]
If you'll make a Pull Request I'll take a look at it :)

**Comment by Balajanovski** [comment]
@NiLSPACE I'm new to github, I thought all I needed was a commit

**Comment by NiLSPACE** [comment]
You don't have write access to the repo. You'll have to fork (button on the top right), and clone that repository. Then you can commit your changes to there and create a pull request back to this repo.

**Comment by Balajanovski** [comment]
@NiLSPACE Thank you

**Comment by Balajanovski** [comment]
@NiLSPACE Figured out how github works and the pull request has been sent, thanks.
Please do not take my inexperience in version control as a sign of inexperience in programming for I can assure you that this is not the case.

**Comment by Balajanovski** [comment]
@NiLSPACE Close the issue?

**Comment by QuImUfu** [comment]
i have a question but i do not understand that much about programming. 
Why don't you check whether there is already soil? 
if the tree is i one chunk, it would work.
if it is between two chunks it would work if the neighbouring chunk has already been loaded. 
The only case in which it wont work is if the tree is between two or four chunks and at least one of them is not loaded.
Why don't you test whether one of the other cases is true and you can intelligently set some dirt blocks (or in case of a high cliff maybe just cancel tree generation) before setting all the dirt blocks and eventually destroy caves, different surfaces etc. ? 
Is the performance impact to high? 
is it not working as i thought (most likely :smile: )?

**Comment by NiLSPACE** [comment]
We can't check for existing blocks because we have to concider chunk borders. If a tree is generating in a chunk we can't check if the chunk next to it. Unfortunately almost every tree (especially the large trees) are different, and because of that it would be very intensive to look if a tree was in one chunk or more.

If it's between two chunk and one of them is loaded already while the other is generating then yes, it could work, but if the other chunk is not loaded we'd first have to wait for it to load from file, or even worse, wait for it to generate the composition of the terrain. The tree generator already is one of the slower generators, and if the time of generating composition in chunks beside it would be added to it it would be even slower.

All these checks and generating would make the generator even slower than it is already, which is not really worth it. 


@Balajanovski This issue will be closed once the PR is merged :)

**Comment by QuImUfu** [comment]
ah, so it is mainly a performance issue.
Thank you for you answer :smile:
