### ISSUE TITLE
Would it theoretically be possible to implement the MCPE protocol in Cuberite?

### ISSUE THREAD

**Issue by DaMatrix** [cuberite/cuberite#3570]
e.g. `Protocol/Protocol_1_9.cpp` contains lots of methods for sending packets, if one were to replace said methods with the MCPE equivalents, would it be possible to have functions that send the MCPE packet(s)?
(Don't know where else to ask this :/)

**Comment by Pokechu22** [comment]
Theoretically, maybe.  However, most of the constants that MCPE uses are different from those on the PC version of the game, so there would probably need to be a lot more work than just writing a new protocol handler.

**Comment by madmaxoft** [comment]
It would be an effort well spent, isolating protocol-specific stuff away from the core game logic.

The only thing making this too difficult / problematic would be if MCPE has different blocktypes. Filtering each chunk as it is being sent would probably kill the performance.

**Comment by mhsjlw** [comment]
There are many differences in not only the protocol but also how the networking in Minecraft: Pocket Edition actually works.

| Minecraft 'Java' Edition                                              | Minecraft: Pocket Edition                                                                                                                                                                                                                                                                                     |
|-----------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Uses TCP sockets with *stream* encryption                             | Uses the infamous RakNet library (UDP) for making packets 'reliable' and also uses similar *stream* encryption all over UDP                                                                                                                                                                                   |
| The original NBT spec.                                                | A crazy frankenstein NBT with varints and other goofy things (also, fully little endian)                                                                                                                                                                                                                      |
| All big endian, pretty standard                                       | It seems that things in both RakNet and Minecraft: Pocket Edition have some things big endian and some things little endian, it appears to be random. No idea if this is a mistake                                                                                                                            |
| Your standard 1.9 chunk format (not a fixed size!)                    | In >1.0.0 A goofy layered chunk format that uses 1.8 style block placement but uses layers similar to 1.9. It also includes version numbers and weird metadata information throughout the chunk (not a fixed size!)                                                                                           |
| Exact same versioning and functionality across Mac, Linux and Windows | Windows 10 has weird crafting glitches (that may have been fixed?) while Android and iOS work fine, no way to indicate what version the client is using to possibly facilitate these quirks. There are also apparently RakNet discrepancies between Android, iOS and Windows 10 in terms of IPv6 byteordering |

Here would be some things that would require changes to actually make this work:
1. Completely modularize the data transport (possibly useful for running over WebSockets)
2. Rewrite RakNet (since the original is a mess, I guess you could still use it though...)
3. Add the new NBT library along with the new chunk format
4. Replace all the current Minecraft data with all the custom Minecraft: PE specific blocks, entities etc.
5. Rewrite authentication and encryption

I personally think that this is **not** a good idea. If you're interested in entering Minecraft: PE this should be implemented as a completely seperate project.

That's my two cents on the subject.

Here's some reading material:
- [RakNet](https://github.com/OculusVR/RakNet)
- [Minecraft: PE 1.0.0 ProtoDef](https://github.com/mhsjlw/pocket-minecraft-protocol/blob/1.0/data/protocol.json)
- [RakNet in ProtoDef](https://github.com/mhsjlw/node-raknet/blob/master/data/protocol.json)
- [PocketMine-MP](https://github.com/pmmp/PocketMine-MP), a Minecraft: PE server in PHP
- [Nukkit](https://github.com/Nukkit/Nukkit), a PocketMine copy-paste job to Java

**Comment by DaMatrix** [comment]
Yeah, I've already established that this wouldn't be possible. I'm gonna put my time into ProtocolSupport (Spigot plugin) because they have WIP PE support. Thanks!
