### ISSUE TITLE
Peaceful mode hostile mobs do not despawn

### ISSUE THREAD

**Issue by willi123yao** [cuberite/cuberite#3622]
Client version:   1.8/1.9/1.10/1.11
Server OS:        Linux
Commit id:        9fa8477b73ce878c631ba875ec10746b4143ba75

### Expected behavior
The hostile mobs should despawn once difficulty changed to peaceful

### Actual behavior
The hostile mobs are still in the game

### Steps to reproduce the behavior
Spawn some mobs, and change difficulty to peaceful.

**Comment by madmaxoft** [comment]
This will need a bit more involved fix - all aggressive mobs should check periodically, if the world they're in is peaceful, and despawn in such a case. In contrast, despawning mobs only upon setting the difficulty would keep the mobs in unloaded chunks.

**Comment by NiLSPACE** [comment]
Do we really have to check them periodically? We only have to check them if they load/spawn or when the difficulty changes right?

**Comment by willi123yao** [comment]
Maybe the mobs in the unloaded chunks should also get checked once the chunk is loaded - hence maybe periodical check will be unnecessary. I have also noticed that after a server restart(maybe chunk reload) after changing the difficulty has caused the hostile mobs to despawn(not confirmed to be the case yet).

**Comment by willi123yao** [comment]
>  In contrast, despawning mobs only upon setting the difficulty would keep the mobs in unloaded chunks

Actually after reloading the chunks the mobs will despawn(e.g. relog into the server), so I suppose that mobs in unloaded chunks will despawn after loading the chunk. Hence, this will just need to remove all hostile mobs in the loaded chunks.

**Comment by madmaxoft** [comment]
@NiLSPACE right, that should be enough - provided that the checks can be put into all relevant places.

**Comment by NiLSPACE** [comment]
It would also prevent the mob from actually showing on the client-side for X ticks.

**Comment by Etmix** [comment]
Hello!
I tried creating a fix for this issue, which you can take a look at in the attachment.
I placed the fix in the Core Plugin though and I am not sure if that is what you wanted.
This is the first time that I am working on a open source project and I just began reading into your codebase so any comment or help is appreciated.

[difficulties.zip](https://github.com/cuberite/cuberite/files/877350/difficulties.zip)

**Comment by Pokechu22** [comment]
Hey Etmix!

The general way to contribute to this project is through [pull requests](https://help.github.com/articles/about-pull-requests/); this helps keep track of changes.

There's several different ways you can actually create a pull request, but for a simple, single-file change, the easiest way to do it would be to change the file on-site instead of manually cloning the repo (but you can also do that if you're familiar with git).  Simply go to the file (in this case, [difficulties.lua](https://github.com/cuberite/Core/blob/master/difficulties.lua) in the core plugin) and click the pencil icon and it will fork the repo for you.  Then paste in your changes.

For the commit message, you'd give a title of something like "Remove monsters when switching to peaceful" and more information in the description (for instance, a link to this issue by mentioning `cuberite/cuberite#3622`).  Then select "Create a new branch for this commit and start a pull request" (the branch name isn't too important but if you want to set it you'd use something like `fix-peaceful-despawns`).

This process can be a bit daunting at first, but it's pretty easy once you've gotten the hang of it.
