### ISSUE TITLE
Add option to disable logging to file

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3660]
It would be convenient to have an option to disable logging to files.

**Comment by worktycho** [comment]
Where would we put such an option? The issue is that if we want to put it in the settings file, then the issue is that we log some stuff to file before settings file is read, so what is the best way handle those log messages?

Specifically all code between https://github.com/cuberite/cuberite/blob/f269565e73a8c0cbdec35bbaaebefcd580a6cd18/src/Root.cpp lines 127 and 160 occur between opening the log file and reading the settings.

**Comment by mohe2015** [comment]
Maybe it could be a command line option?
