### ISSUE TITLE
Can't see other player running/jumping/something like this

### ISSUE THREAD

**Issue by JohnHenry91** [cuberite/cuberite#3790]
Client version:   1.1.2
Server OS:        Linux Ubuntu 16.04

I can't see other player. They stay only on the spawning place. When I beat them, than I can see they running or crafting. After a reconnect the same problem comes up.

**Comment by mathiascode** [comment]
Tachaway reported this in the IRC channel as well. 

"ah, hi, was just trying the server, other player movements aren't being shown correctly though, get rotation etc. but they seem frozen on the spot, have I failed to configure something or is it a bug -.-

tried building from source and the available binaries on 64 bit debian but aye, rooted to the spot"

**Comment by JohnHenry91** [comment]
I compiled cuberite on my 64 bit server and a BananaPi. With both systems I have this problem. I tried it in my Local Area Network and through the internet (DynDNS and Portforwarding is activated).

**Comment by mathiascode** [comment]
Does this happen in MC versions below 1.12?

**Comment by JohnHenry91** [comment]
I tried it today and yes - I tested 3 versions on two Clients and then Problem is in every Version available...

**Comment by lkolbly** [comment]
I'm having this issue as well, using two clients both on version 1.11.2. (also briefly tested with one client at 1.11.2 and the other at 1.12, same issue).

Essentially, have both clients login, each will see the other rooted to their spawn position. If they ender pearl, etc., the teleport will be displayed to the other client.

If client A punches client B, then A will see B teleport to their actual position, and will see B moving around in the future (but B will still see A rooted to the spot).

Printing out SpeedSqr in BroadcastMovementUpdate (line 1919, right before if (!m_bHasSentNoSpeed)) shows that the player speed is fixed at zero (even as they move around), until they get punched, at which point m_Speed jumps to a vector of length 11 (SpeedSqr=121).

A quick look at git blame and I blame commit 2b699dc749b1827e47943f148f57dfe2e03f3a75 (from #3739, merged in early June), which adds the if (!m_bHasSentNoSpeed) conditional (forcing that conditional to happen fixes this problem for me).

Though I suspect that m_Speed is not being set correctly, since it's zero even as the player moves around. If it were non-zero when the player moved around (before being hit), this problem would be fixed as well.
