### ISSUE TITLE
API Documentation should have a section for contributing to the docs itself

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite#3896]
While trying to find a solution to #3886 and #3887, I was surprised to see no instructions on updating the API docs themselves.
The [CONTRIBUTING.md](../tree/master/CONTRIBUTING.md) file should include guidelines and instructions for updating the API docs.
The API documentation homepage should have a section on contributing to and updating itself. This section should point out that documentation is not held in the [/docs](../tree/master/docs) folder, but rather in the [APIDump](../tree/master/Server/Plugins/APIDump) plugin folder.

Also, in the future, I would like to see all compiled documentation held in the [/docs](../tree/master/docs) folder.

Wonder how I put links to the source code files and folders in this issue? Simply prefix the link with `../tree/master/`.  Ex: `[text](../tree/master/README.md)` Replace master with whatever branch you're trying to link to (however, I recommend against this as other branches may be deleted under your nose)

**Comment by madmaxoft** [comment]
The `/docs` folder contains the documentation aimed at server developers. Perhaps it could be renamed to `dev-docs`?

We can't move the Lua API documentation into that folder, simply because it is generated from a running server, which may very well be without the source tree structure around it (and in fact that is how the apidocs web is updated automatically).

**Comment by williamhatcher** [comment]
I think renaming the `/docs` folder to `/dev-docs` is a good idea.

**Comment by williamhatcher** [comment]
@madmaxoft , should we go ahead with this?

**Comment by madmaxoft** [comment]
Sounds good. Make a PR, we'll see if there's anyone against.
