### ISSUE TITLE
World freezes Cuberite on startup

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4078]
Client version:   1.12
Server OS:        Linux
Commit id:        0dd172b80ffc949cf87119ad2003589d7eb82c46

This world from my server Cuberite when the server tries to load it on startup, and sometimes crashes Minecraft when loading it in single player. The problem is redstone related, I believe someone placed a ton of redstone with WorldEdit.

World: https://nofile.io/f/UYFpKO7dDKu/world.zip

Single player crash report: [crash-2017-11-26_18.11.48-server.txt](https://github.com/cuberite/cuberite/files/1504049/crash-2017-11-26_18.11.48-server.txt)

**Comment by Mindavi** [comment]
When I try to start the Cuberite server with this map, the server doesn't even boot up properly. Also, I see you're using a modified (Wurst) client, did you ever try if an official client worked? I'm gonna look into why the server doesn't boot up properly. If I find anything worth sharing, I'll update here.

**Comment by Cl1608Ho** [comment]
Based on your descriptions it seems like something in the world (eg too much Redstone) takes too long to process and blocks the tick for many seconds, upon which it's terminated.

Might wanna try reducing the amount of chunks ticked by default / prepared?

**Comment by Mindavi** [comment]
I'm not sure how to do that, but disabling redstone (RedstoneSimulator=Noop) prevents the crash from happening. It seems like (100,0) contains loads of redstone dust stacked upon each other. My vanilla client and the cuberite server both have lots of problems keeping up when I come near the heaps of redstone, even when redstone simulatoer is disabled (not sure if the client tries to tick the redstone or if it's all done on the server side). My client doesn't crash however.

The provided crash log says it all, a stack overflow happens because there are too many break ticks (presumably because you're not allowed to stack redstone like it were) at once.

If anything like this happens, it's probably up to the server owner to open up the map in mcedit or so and fix it, or roll back to a backup. I don't think this is up to cuberite to fix.

Vote to close this issue. 
![screenshot-24-08-2018_11 49 47](https://user-images.githubusercontent.com/9799623/44579038-6c13c200-a795-11e8-9c10-194df27bb1d9.png)

**Comment by mathiascode** [comment]
No longer an issue.
