### ISSUE TITLE
Certain block entities cause memory leak

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4079]
Client version:   1.12.2
Server OS:        Linux
Commit id:        (Found at the top of the server's console output)

### Expected behavior
Memory leak doesn't occur when placing chests, hoppers, droppers and trapped chests (with WorldEdit?).

### Actual behavior
Memory is never freed.

### Steps to reproduce the behavior
1. Install WorldEdit.
2. Type `//sphere chest 20` in chat
3. RAM usage has increased a lot

**Comment by peterbell10** [comment]
On the linked PR there is still a large increase in RAM usage and I'm pretty confident it isn't a leak because RAM usage goes back to zero after issuing the stop command.

I think it just genuinely takes a lot of RAM.  Some back of the envelope calculations:
 * A sphere of radius 20 is ~35,000 blocks
 * Each chest has has a 3x9 inventory or 27 `cItem` instances.
 * On my machine a `cItem` is 192 bytes.
 * Therefore each sphere has ~173MB of `cItem`s.

Then I think the sphere will exist twice, once in the actual world and once in WorldEdit's undo stack.  Clearly using hundreds of megabytes for empty chests is hugely wasteful though.  It might be worth looking into lazily allocating the chest's storage or reducing the size of an empty `cItem`.

**Comment by peterbell10** [comment]
I'm going to look into making `cItemGrid` allocate lazily.  That way chests won't take any memory until items are put into them.
