### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by dynematic** [cuberite/cuberite#4174]
Client version:   1.12.x
Server OS:        Linux/ (Ubunutu 16.04)
Commit id:       95108c134d410040efadfa6bb00c8ce3486fb7fa

### Expected behavior
Everyone on the server should be able to see everyone.

### Actual behavior
2 players joining..

First player to join the server can't see the 2nd player to join.
_(First player can see the 2nd player placing blocks, opening doors..)_

BUT the 2nd player to join can **see** the first player!

### Steps to reproduce the behavior
- Compile cuberite or download finished.
- Add old world, world_nether.. to the dir of cuberite Server.
- Launch server. 
- Stop server.
- Change spawn cords in world.ini, and some motd.

Join server, let you friend join. Friend will see you but you won't see your friend.

(Could we call it a paradox?)

**Comment by bearbin** [comment]
Thank you for reporting this issue. It is, unfortunately, a known issue and we're not quite sure what causes it. This duplicates #4082, #4049, #3696. 

If you have any more information about the circumstances surrounding this bug, please do let us know. Otherwise I am going to close this issue as a duplicate.
