### ISSUE TITLE
Spawning Agent from very beginning

### ISSUE THREAD

**Issue by jamespinkerton** [cuberite/cuberite#4195]
Hi. It looks like agent's can't connect when a new server is spawned for several ticks. Is there a way to ensure that an agent is spawned on the first tick when this is possible?

Thanks so much,
James

**Comment by madmaxoft** [comment]
What do you mean by Agent?

**Comment by jamespinkerton** [comment]
By agent I mean a client

**Comment by madmaxoft** [comment]
I'd say this is expected behavior with the current implementation. The client network communication is parsed within the world's tick thread (to avoid race issues), and the login handshake means that several messages need to be exchanged back and forth; each such exchange consumes at least one world tick.

Do you have a scenario where this behavior is a problem?

**Comment by peterbell10** [comment]
Closing as this is expected behaviour.
