### ISSUE TITLE
What about unifying the way header files are referenced?

### ISSUE THREAD

**Issue by gregchu1** [cuberite/cuberite#4236]
Client version: 1.12.2
Server OS: Linux
Commit id: b9fdaf8

Hi. While I was looking through the code to fix other problems in the game,
I have found that the files in `src` folder each have a different reference method.
The `Chunk.h` file exists in the `src` folder, but the way the files in `Blocks`,
which is a subfolder of the `src` folder, refers to this header file differs.
![3](https://user-images.githubusercontent.com/37770967/41054565-38682ae2-69ae-11e8-9f00-be2f9cc79ccd.jpg)
Only 3 of the 8 files including `Chunk.h` are shown above.
(Files in the `Blocks` folder : `BlockHandler.cpp`, `BlockLever.h`, `BlockTorch.h`)
The other five files contain `Chunk.h` in the following way:
(Files in the `Blocks` folder : `BlockButton.h`, `BlockDoor.h`, `BlockRedstoneRepeater.h`,
`BlockSignPost.h`, `BlockWallSign.h`)
![6](https://user-images.githubusercontent.com/37770967/41054784-e54a229c-69ae-11e8-874c-477bb26b0e59.jpg)
I think the above method can make `Chunk.h` mistaken to exist in `src/Blocks`.
Even if this code works, would not it be better to match the reference method to avoid confusion?

**Comment by NiLSPACE** [comment]
> Even if this code works, would not it be better to match the reference method to avoid confusion?

Makes sense. 👍

**Comment by peterbell10** [comment]
I agree that it's a good to be consistent but I think I would prefer if include paths were always relative to the src/ folder, e.g. the example above would become
```cpp
#pragma once

#include "Blocks/BlockHandler.h"
#include "Chunk.h"
```
even though the file is already in the Blocks folder.

IMO this has a number of nice properties:
 * Error messages never contain paths like `src/Entities/../UI/../Entities/Minecart.h`
 * Every include statements for a given file is the same
 * Paths like `/usr/include/../` are never searched for the header

There's also that fact that the precompiled header on MSVC can't be included like this
```cpp
#include "../Globals.h"
```

**Comment by madmaxoft** [comment]
I personally prefer includes to be explicitly specified relative to the where they are referenced from. It just feels much more organized, than randomly depending on the include-path setup by the environment. It tells you immediately what file to open, rather than search for.

As for the path search, includes in dquotes shouldn't be searched in the system headers anyway, if I remember correctly.

**Comment by peterbell10** [comment]
> It just feels much more organized, than randomly depending on the include-path setup by the environment.

I don't think that either is really any more or less organised. As long as you use one of them consistently then they both tell you exactly where the file is. Also it appears to have been a deliberate choice to support src relative includes:
https://github.com/cuberite/cuberite/blob/01e72ddb6567531b16f92af2564b853878b6ef65/src/BlockEntities/CMakeLists.txt#L3

>As for the path search, includes in dquotes shouldn't be searched in the system headers anyway

I think is still does search system include but [apparently the priority is higher for local headers](https://stackoverflow.com/questions/3162030/difference-between-angle-bracket-and-double-quotes-while-including-heade).  I guess it's not going to be an issue in practice anyway.

At the end of the day I think consistently using one method is much more important than which method is actually being used.

**Comment by madmaxoft** [comment]
> Also it appears to have been a deliberate choice to support src relative includes:
That is actually only to support the `Globals.h` madness that we succumbed to. And it doesn't even need to be that way, only later I found out there's a MSVC flag to enforce a global header in all translation units, so that should have been used instead. One of these days I'm gotta fix it :)

Consistency is indeed the best. And I believe we've been using the relative-to-current-file forever, with only a few exceptions that were spotted here.
