### ISSUE TITLE
Lilypads reset water physics in water non-source blocks

### ISSUE THREAD

**Issue by csunday95** [cuberite/cuberite#4255]
Client version:   1.12.2
Server OS:        Linux (CentOS7)
Commit id:       06eb5cc70da76f6a95afa9c9a3d692ca39e39a76

### Expected behavior
Lilypads cannot be placed at all upon non-source flowing water; right clicking while a lilypad is equipped on flowing water is completely ignored

### Actual behavior
Lilypad momentarily appears on block under flowing water, but is immediately displaced by water attempting to flow onto that block and becomes an item

### Steps to reproduce the behavior
(1) Place a water source block such that blocks of flowing, non-source water are created
(2) attempt to place a lilypad upon a block of non-source flowing water such that the viewing angle also intersects with a block underneath the water

**Comment by tympaniplayer** [comment]
This will happen no matter what type of block you place it on, try placing it on a dirt block. The only block it doesn't work for is air. There is a check for `if (a_BlockFace > BLOCK_FACE_NONE)` which just makes sure you aren't placing it on air, otherwise it is placed. I'm seeing if I can figure this problem out. Pretty new to the project so it may be slow going 🙂
