### ISSUE TITLE
Server slowing to a crawl

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#4271]
Client version:   1.12.2
Server OS:        Linux
Commit id:        90d552a702a435f644c29f75fc2a85c0d71ee510

The server is spitting SetSwimState failures all over the place and using 100% of a single core.
Video: https://youtu.be/fw4GpIy_xhg

**Comment by peterbell10** [comment]
I think you have the causal relationship backwards. I'm pretty sure what's happening is:

Server is slow -> Chunks aren't generated fast enough -> `cChunk::UnboundedGetRelBlockType` fails -> Set swim state logs an error

And the server might just be slow because it's a debug build.  Were you generating a lot of new terrain before noticing this?

**Comment by Bond-009** [comment]
That's possible, but I was first experiencing issues in Release mode and switched to Debug to take a closer look at what could the issue. I'm also 99% sure no new terrain was being generated at that moment.

**Comment by peterbell10** [comment]
Interesting, can you think of anything else that might be causing the slowdown?  Does it only happen with that world?

**Comment by Bond-009** [comment]
At the moment I can't really test if it's the world causes the issue but what I can tell you is that it only happens when a player is connected.
The world: https://bond009.stackstorage.com/s/bmrK3L8V5Nm9gIg

**Comment by peterbell10** [comment]
It appears to be a problem with ocelot spawning.  There are over 2000 entities, mostly ocelots, being ticked on the server near to your base and there are some O(n^2) algorithms that are making it slow to a crawl.
