### ISSUE TITLE
Announce protocol version (Stevenarella client support)

### ISSUE THREAD

**Issue by earboxer** [cuberite/cuberite#4335]
Client version:   [Stevenarella](https://github.com/iceiix/stevenarella/) 10e5d6f44186c6acdf87666a6f00744d20744d0c
Server OS:        macOS
Commit id:        e6d805d3229a0b56426973cbeb07ada033d363d1

### Expected behavior

Cuberite tells Stevenarella what protocols are supported, Stevenarella connects using one of those supported protocols.

### Actual behavior

Cuberite doesn't tell Stevenarella what protocol to use, Stevenarella defaults to 477 (1.14). Cuberite says that that version is not supported, client cannot connect.

Stevenarella log message

>[main.rs:99][WARN] Error pinging server 127.0.0.1 to get protocol version: Err("Wrong packet"), defaulting to 477

message on screen
> {"text":"Unsupported protocol version 477, please use on of these versions: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x"}

> protocol error: Wrong packet

### Steps to reproduce the behavior

* clone https://github.com/iceiix/stevenarella
* have rust installed, `cargo run --release` to build and launch client
* have cuberite server running
* try to connect to cuberite server (127.0.0.1) in Stevenarella

**Comment by iceiix** [comment]
In the status check, Cuberite is sending a StatusResponse packet in response to StatusPing, instead of the expected StatusPong.

```rust
        let status = if let Packet::StatusResponse(res) = self.read_packet()? {
            res.status
        } else {
            return Err(Error::Err("Wrong packet".to_owned()));
        };

        let start = Instant::now();
        self.write_packet(StatusPing { ping: 42 })?;

        if let Packet::StatusPong(_) = self.read_packet()? {
        } else {
            return Err(Error::Err("Wrong packet".to_owned())); // errors out here
        };
```

If I change Stevenarella to accept StatusResponse in response to StatusPing, then it can connect to Cuberite (and negotiates the protocol correctly). But I think Cuberite should reply with pong (0x01) instead of a duplicate StatusResponse (0x00). Looking at the code I'm not sure why it doesn't, looks like it is meant to:

https://github.com/cuberite/cuberite/blob/24a8456f79aa35cfe8c3859c880e1bffeae088c6/src/Protocol/ProtocolRecognizer.cpp#L1244-L1254

**Comment by tigerw** [comment]
Could you test again? There were some recent changes with regard to status handling.

**Comment by earboxer** [comment]
Yes. This works as expected (using Stevenarella from master, and cuberite from easyinstall.sh).
