### ISSUE TITLE
Development: Create pre-commit hook to check changed files for standards violations

### ISSUE THREAD

**Issue by earboxer** [cuberite/cuberite#4336]
While I'm a big fan of code standards, it's a little annoying every time the pipeline comes back failing, and I have to write another commit.

We should have a shared pre-commit hook to make it harder to make those sorts of mistakes. Then we can symlink it to `.git/hooks` to set up our development environments.
The hook should check the modified files (`git diff --cached --name-only`) for

* CheckBasicStyle.lua
* clang-tidy
* anything else?

It also might be nice if the hook could fix based code style problems. (The hook should only `exit 0` if all checks passed and no code was changed).

**Comment by peterbell10** [comment]
Part of what you want is already covered by [CONTRIBUTING.md](https://github.com/cuberite/cuberite/blob/master/CONTRIBUTING.md#pre-commit-hook). You could also run the [clang-tidy script](https://github.com/cuberite/cuberite/blob/master/clang-tidy.sh) if you wanted but I don't think the clang-tidy run is incremental so you might find it's too slow.

IIRC, passing `-fix` to clang-tidy will apply the suggested fixes. Updating CheckBasicStyle to support a similar option would probably require a lot of work though.

**Comment by pwnorbitals** [comment]
Could we auto-install the pre-commit hook in some way ? Otherwise, we can just close this isssue

**Comment by tigerw** [comment]
Tentatively closing; the current style checks run too slowly to be enforced through a hook, especially since many contributors tend to make a lot of commits and only squash them when the PR is merged.

I'd suggest running `./clang-tidy.sh` and `cd src && lua CheckBasicStyle.lua` and also doing a clang build (most pedantic) before pushing; that tends to catch the vast majority of CI errors locally.
