### ISSUE TITLE
API: Crash on call to cWorld:SpawnSplitExperienceOrbs

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4352]
Server OS:        Windows
Commit id:        (9dc1343bda0592f2d27bb216eb21fdec97f73945)

### Expected behavior
Server should not crash

### Actual behavior
Server crashes

### Steps to reproduce the behavior
1) Add this code to a plugin inside a command handler
2) Call the command
`cRoot:Get():GetDefaultWorld():SpawnSplitExperienceOrbs(nil, 1)`

**Comment by masp** [comment]
@Seadragon91 
This is happening because you're passing `nil` to the function for the position argument where the position needs to be a valid `Vector3`. 

This is still a bug IMO, since it would be good if this was logged as a plugin error instead of crashing the whole server.

Here's a simple plugin that shows how the function can be used correctly:
```lua
function Initialize(Plugin)
    Plugin:SetName("Test")
    Plugin:SetVersion(1)

    cPluginManager.AddHook(cPluginManager.HOOK_CHAT, OnChat)

    LOG("Initialized " .. Plugin:GetName() .. " v." .. Plugin:GetVersion())
    return true
end

function OnChat(Player, Message)
    -- Player:GetEyePosition() returns a Vector3 which SpawnSplitExperienceOrbs requires as the first argument
    cRoot:Get():GetDefaultWorld():SpawnSplitExperienceOrbs(Player:GetEyePosition(), 1)

    return false
end
```
