### ISSUE TITLE
here has some work for a beginner with code?

### ISSUE THREAD

**Issue by Aplaus228** [cuberite/cuberite#4368]
if someone has easy work I will do it just write it on the comment.

**Comment by madmaxoft** [comment]
It is quite rare to have a very simple issue here. But perhaps if you don't mind writing Lua code instead of C++, you could have a look at the Core plugin, which is an integral part of Cuberite and it seems to have a few Easy issues in it: https://github.com/cuberite/Core/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
