### ISSUE TITLE
BlockHandlers: Verify CanBeAt checks

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4677]
Many of the blocks check in their `CanBeAt` function if they are attached to a fully solid block; some blocks include a check for the top-side of a top-half-slab, some blocks include a check for the bottom side of a bottom-half-slab. Some blocks only check for air. Most of these should probably use the very same logic, they most likely just weren't "found out" as buggy yet.

All the `CanBeAt` functions should be revised and if many of them use the same "solid face" check, this check should be pulled into a separate helper function in `cBlockHandler`.

**Comment by ChaosCat** [comment]
Hello! I discovered the repo yesterday and would like to contribute. I'd like to take this one on

**Comment by madmaxoft** [comment]
Good luck :)

**Comment by ChaosCat** [comment]
Ok so I've finished going over all the implemented CanBeAt-s and this is a summary of things I noticed = there that probably should be changed (A full list in an evernote note):

- abstracting some of the functions (getSurface block instead of rel-pos.y - 1
  - Supporting blacklist/whitelist for more dynamic code design
- Main dispatcher for block checks
- Unify height checks
- Use consts for bitmasking on block meta information
- Some end-of-chunk checks

Thus I think that it may be appropriate to implement the following general "dispatcher" function
which would forward the per-block calls to this one with the appropriate parameters
- Precompiled lists of whitelists/blacklists in const formats (For block validation)
- Mandatory global height validation (flexible range for edge cases)
- ChunkEdges check switch (for stuff that can't be animated)
- General surrounding function with block whitelist/blacklist
- An optional list of bool callbacks for additional really special checks in case (this would usually be empty/null)

I think it's most appropriate to be implemented in cBlockHander as a generic helper function, not sure about where to get the consts and pre-defined white/blacklists. This would cause a very little overhead and would make it much easier to add logic to these kinds of blocks while encapsulating most of the repetitive logic.

**Comment by madmaxoft** [comment]
I admit I have no idea what you mean by "dispatcher". But since each block type already has a virtual `CanBeAt` function, I'd call that a dispatcher, no need to go from a virtual call back to a base class just to be switched on the blocktype again.

This issue was meant more for cleaning things up - many blocks check for solidity below them, but do so using various methods, some of them incomplete. So I'd extract the `IsBlockBelowSolid` function into the base `cBlockHandler` and make the descendants call that.

No need to go refactoring this big time, because it will need to be refactored again for the 1.13+ blocktype support. Note that this mostly negates the need to use named constants for the bit twiddling, because *all* those bits will get removed.

**Comment by ChaosCat** [comment]
Fine then, so I guess I'll just create all those static functions for different types of filters and add a checkAbove generation. 

The basic idea of a was that: CanBePlacedAt called for the block, the function would look much flatter, since there are also a lot of tidbits like slab position checks torch neighbour block faces, portals weird behavior
Fot example for cactus:
CanBeAt():
if not HeightBoundariesCheck() return false
if not IsAbove(ALLOWED_BLOCKS) return true
if HasBlocksAround(SOLID_BLOCKS_LIST, radius=1) return false
return true

But I get what you mean by simple refactors if a rework is going to happen. I'll just chop in some helper functions to cBlockHandler and use these there while tidying them up

**Comment by ChaosCat** [comment]
Just noticed that most of the relative block checks don't use the Unbounded variant, there could be cases when placing at the end of chunk in height (e.g flowers) or width (e.g Button). Is this a bug that should be corrected?

**Comment by madmaxoft** [comment]
`Unbounded` access is needed only for horizontal neighbors, vertical neighbors are always present. So for horizontal neighbors, fix those that aren't using the `Unbounded`.

**Comment by ChaosCat** [comment]
Oh I see, so I'll revert the ones I changed and PR it.
