### ISSUE TITLE
Advanced rotate function for cBlockArea

### ISSUE THREAD

**Issue by YaroshenkoYaroslav** [cuberite/cuberite#4691]
I just can’t understand why you need so much inferior function to rotate area: 
- RotateCCW
- RotateCW

Why not create a function "Rotate" that takes 3 arguments (x, y, z).
And yes, why the rotation angle should be a multiple of 90?

**Comment by bearbin** [comment]
Rotations should be reversible, rotations are not defined for many
blocks in the x/z-axes. You can never have a furnace pointing
upwards for example. Thus we only have rotations around the y-axis and
reflections in the x/z-plane which doesn't really make sense but is at
least reversible.

Rotations by non-90 degree angles make not much sense in a orthogonal
voxel world. How do you rotate a cuboid by less than 90 degrees without
breaking the relationships between blocks?

And you can't break relationships between blocks because of multi-block
structures (and virtual multi-block structures using CanBeAt).
