### ISSUE TITLE
NBT parsing failed when many furnaces are placed and server is restarted

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4696]
Client version: 1.12.2
Server OS: Linux

### Actual behavior
Server regenerates chunk, when server is restarted

### Steps to reproduce the behavior
I attached a zip file with the [world](https://github.com/cuberite/cuberite/files/4547452/world.zip) that causes the error:
```
Loading chunk [-2, 1] for world world from file r.-1.0.mca failed: NBT parsing failed. Offloading old chunk data to file world/region/badchunks/ch.-2.1.2020-04-28-19-22-23.dat and regenerating chunk
```
Use worldedit to place many furnaces. Restart the server and the error appears.

**Comment by madmaxoft** [comment]
Caused by: https://github.com/cuberite/cuberite/blob/38080c7cac939c433af6c19e8173339bfdb0b68e/src/WorldStorage/FastNBT.cpp#L252-L263

Basically it's a protection against invalid / malicious huge NBT data, it's allowing only 10k items in each List element, but since a chunk can have as many as 65k furnaces, each having a list entry, this is triggered.

We could increase the limit, but what is a good limit? Any number will sooner or later be too small.
I was thinking perhaps adjust the limit dynamically - when there's `N` bytes left in the data, there can't be more than, say,  `N / 2` list items; if the count says there's more, it's invalid / malicious NBT. The caller already knows how much data it's passing to the `Parse` function so they have a relative measure of how much memory will be needed for the parsed data.
