### ISSUE TITLE
[BUG] When destroying a block with a pressure plate on it, only Wooden Pressure Plate drops

### ISSUE THREAD

**Issue by 0ddlyoko** [cuberite/cuberite#4795]
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: 46398f4671012a0d913bd7bc0c70ffdc2645f2ac 

### Expected behavior
Pressure plates should drop

### Actual behavior
Only wooden pressure plate drops

### Steps to reproduce the behavior
- Place a block
- Place a Wooden Pressure Plate on the block
- Destroy the block
- The Wooden Pressure Plate is dropped
- Do the same with Stone, Gold & Iron Pressure Plate
- These three Pressure Plate don't drops

### Server log
```
/
```

**Comment by 0ddlyoko** [comment]
I'll try to fix it (That will be my first commit !)

**Comment by 0ddlyoko** [comment]
Same with Wooden / Iron Doors (Wooden Doors drop but not Iron Doors)

**Comment by ion232** [comment]
Okay, so I've looked into this and it's because of these lines in 
[cItems cChunk::PickupsFromBlock(Vector3i a_RelPos, const cEntity * a_Digger, const cItem * a_Tool)]

This is where the problem lies. The default item handler is used to determine whether the items are harvestable or not, because the block that is being undermined (e.g. pressure plate) isn't destroyed by a tool.
Unfortunately, it thinks that the stone pressure plate, etc, are not harvestable, because you can't normally harvest them with no tool in your hands.

https://github.com/cuberite/cuberite/blob/f65679d1d4ca84dcb5bdeffacf9e815c2cc539b6/src/Chunk.cpp#L966

auto toolHandler = a_Tool ? a_Tool->GetHandler() : cItemHandler::GetItemHandler(E_ITEM_EMPTY);
auto canHarvestBlock = toolHandler->CanHarvestBlock(blockType);
bool cItemHandler::CanHarvestBlock(BLOCKTYPE a_BlockType);

It doesn't seem obvious to me exactly how a change should be implemented for this, because you can't just edit CanHarvestBlock, or it would allow players to mine iron doors with their hands, etc. I was going to make a new item handler but then Visual Studio decided it didn't feel like importing ItemHandler.h, so I'm just going to give up on it and leaving this message here in case someone else wants to try it.

**Comment by tigerw** [comment]
I feel there was a regression somewhere, but a potential fix might be to pass along the digger data to any DigBlock caused by the player.

Perhaps it's Vanilla who's behaving strangely here. What's the point in making iron doors/stone plates undroppable without the right tool, if you can break the block under them with any tool, and get the item anyway? 🤔

**Comment by ion232** [comment]
I presume it's because punching an iron door takes a while to complete (therefore not accidental), but undermining it is quite easy to do accidently and you wouldn't want to punish the player for that, considering the amount of resources it requires to make. Still a good point though.

**Comment by 0ddlyoko** [comment]
> Okay, so I've looked into this and it's because of these lines in:
> https://github.com/cuberite/cuberite/blob/f65679d1d4ca84dcb5bdeffacf9e815c2cc539b6/src/Chunk.cpp#L958
> 
> This is where the problem lies. The default item handler is used to determine whether the items are harvestable or not, because the block that is being undermined (e.g. pressure plate) isn't destroyed by a tool.
> Unfortunately, it thinks that the stone pressure plate, etc, are not harvestable, because you can't normally harvest them with no item in your hands.
> 
> https://github.com/cuberite/cuberite/blob/f65679d1d4ca84dcb5bdeffacf9e815c2cc539b6/src/Chunk.cpp#L966
> 
> 
> https://github.com/cuberite/cuberite/blob/f65679d1d4ca84dcb5bdeffacf9e815c2cc539b6/src/Chunk.cpp#L967
> 
> It doesn't seem obvious to me exactly how a change should be implemented for this, because you can't just edit CanHarvestBlock, or it would allow players to mine iron doors with their hands, etc. I was going to make a new item handler but then Visual Studio decided it didn't feel like importing ItemHandler.h, so I'm just going to give up on it and leaving this message here in case someone else wants to try it. But even a new item handler is a bit hacky, given that a new item type equal to -2 or something would need to be introduced, just to handle this edge case.

We could make a new method `DropNaturally(Vector3_i)` that will drop this block without calling `cChunk::PickupsFromBlock(Vector3i a_RelPos, const cEntity * a_Digger, const cItem * a_Tool)`.

I was going to fix this bug but here I'm working on another bug, when I've ended with the other bug I'll try to fix that

**Comment by tigerw** [comment]
How about, in the PickupsFromBlock line you highlighted, instead of always calling CanHarvestBlock, say `if ((a_Tool == nullptr) || a_Tool->CanHarvestBlock()) { // call PickupsFromBlock }`. So we drop stuff if a_Tool == NULL, i.e. it was a natural drop.

Of course need to go through everything to make sure this doesn't cause things which don't normally drop to start dropping. Also remove the a_Digger parameter in PickupsFromBlock, doesn't seem to be used.

**Comment by tigerw** [comment]
Regression #4505
