### ISSUE TITLE
Beds don't obey colors when dyed.

### ISSUE THREAD

**Issue by koutsie** [cuberite/cuberite#5162]
Client version: 1.16.5
Server OS: Linux (Armbian)
Cuberite Commit id: 01a4e696b3d2c973cdd1fb4345d747bd10e93ad9

### Expected behavior
Bed have the color that they were dyed to.
![image](https://user-images.githubusercontent.com/18449778/111887374-662dfe00-89dd-11eb-84f8-c7351346e519.png)

### Actual behavior
Beds just become red.
![image](https://user-images.githubusercontent.com/18449778/111887378-69c18500-89dd-11eb-84aa-4b70d7503609.png)

### Steps to reproduce the behavior
Get bed.
Dye bed.
Place bed.

**Comment by tigerw** [comment]
I remember beds changing colour yesterday when I was testing them, could you confirm the client version? I don't think we support 1.16.5 yet.

**Comment by 12xx12** [comment]
You are connecting from a 1.16.x client, this is not supported. Please try again without the proxy (or whatever you are using)

**Comment by koutsie** [comment]
They just turn red on 1.9.4 at least.

**Comment by tigerw** [comment]
According to the MC wiki dyed beds only got added in 1.12, and it appears to work well on that version. We're still working on 1.13+ support.

**Comment by Pokechu22** [comment]
Dyed beds used, if I recall correctly, a _block entity_ to store their color in 1.12 (due to the limited number of remaining IDs); it looks like cuberite implements this in [BedEntity](https://github.com/cuberite/cuberite/blob/master/src/BlockEntities/BedEntity.h).  In 1.13, they were moved to separate blocks for each color (using block states for direction).  Some kind of special conversion code would be needed to handle the block entity into separate blocks (or separate blocks into block entity) setup.

**Comment by tigerw** [comment]
Right, so we'd need a dummy BE that reads the colour off its block type to remain compatible with 1.12.

**Comment by tigerw** [comment]
But for now, closing bc works in 1.12.
