### ISSUE TITLE
API docs are down

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#5559]
@bearbin Looks like https://api.cuberite.org returns a 502 response.

**Comment by bearbin** [comment]
Sorry I hadn't got around to fixing this yet - the issue is with @madmaxoft's server that hosts the docs. It seems like the hosting provider has banned the IP of the reverse-proxy server that I host...

I noticed that you created a new repo for the docs @mathiascode so moving across to GH pages to host seems like a good idea.

**Comment by bearbin** [comment]
In the meantime I've set the domain to redirect to the old site on xoft.cz instead of reverse-proxy.

**Comment by mathiascode** [comment]
No worries. I was planning on migrating the API docs to GitHub Actions in any case, since they haven't been updated since 2022.

The api-docs repo now contains a workflow to build and publish the docs. You should be able to add the `api.cuberite.org` domain in the repo settings.

The docs can be previewed here: https://cuberite.org/api-docs (should start redirecting to https://api.cuberite.org once the domain is set up)

**Comment by bearbin** [comment]
DNS updated, just waiting for it to propagate and HTTPS to get enabled on the GH pages side.
