### ISSUE TITLE
Moving Towards 1.0

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#874]
Ok, I thought of a new proposal for branching and everything else. I still believe that the stuff down at the bottom of this post is a good idea, but it's a long way off still. 

For now, I think we should have a development branch where all dev work happens. Every week (perhaps every saturday or something) we would see if the branch has no major corruption/crash/huge resource consumption type bugs, then merge it into master. 

The buildserver would only build from master, so hopefully the number of crash bugs and other major issues getting into users' hands.

What do you think?
### Please ignore all below this line. It is old and might not have been updated for a while.

I was thinking about what it would take to produce a stable release, ready for "production". Our v1.0. This issue will contain what is needed to get there, and how we might go about when we stabilise. 
## Requirements

These are just some I could think of from the top of my head, so please give your own objectives, and tell me when some are completed. 
### Gameplay
- Redstone Compatibility
- Minecarts
- The End, and the Enderdragon
- Villagers, Villages and Trading
- The Nether, and Portals
- Command Blocks (optional)
### Plugin API
- Stabilised and debugged.
- Documentation completed and a startup guide written.
### Performance
- ~~Double the players with the same RAM and CPU.~~ (Chunk sparsing completed)
### Usability
- User manual or installation and usage guide available.
- ~~Vanilla commands basically replicated.~~
## What If We Get There???
- Tagged stable releases in their own branch.
- Release branch for only stable stuff and bugfixes. Would be the default for downloads.
- Debian Package?
## What To Do Afterwards?
- Performance!
- Modularise - performance and bugfreeness comes here.
- Test, test test. Get a testing framework and make it work.
- Cut LOC and complexity - refactor.
- Backport fixes to earlier versions - keep multiple stable versions for different minecraft releases?
- Standard keeping up with Mojang work.

Of course, these are just my thoughts for what we might do - please say what you think about this issue (and debate if we're actually going to reach this point in the first place).

**Comment by wiseoldman95** [comment]
Anything done yet? A stable branch should be easy.

**Comment by tigerw** [comment]
Some things, sort of, but nothing fully/completely functional.

**Comment by wiseoldman95** [comment]
I meant asking about having a stable branch :P

**Comment by yangm97** [comment]
I feel like this could speed up development while having a equally, maybe more stable branch. Instead of doing in-game testing for each PR, the development branch would get updated with (finished) features in need of testing. 

It may be a good idea to have public builds from the dev branch too, so those who like living in the bleeding edge can report real world issues that could go unnoticed by developers testing PRs individually.

The weekly release cycle seems reasonable to me. Also, what you described (or what I understood from it) looks pretty much like [Git Flow](https://guides.github.com/introduction/flow/).

**Comment by ard1998** [comment]
Well, the state of the project is that we have too many unfinished / missing functions for make an stable version. We can do a version freeze, so we can focus on 1.9 1.10 support 1.11 support. (1.8 has in my opinion too many differences from the later versions) and make an stable version for that, we can go for supporting new protocols in development.

**Comment by LogicParrot** [comment]
We've actually already tried a freezing / branching model for a while and it wasn't productive at all to development. There wasn't - and still isn't - enough developer power to meaningfully maintain several branches, and the "frozen(testing)" branch and the "stable" branches practically lagged behind forever, and everyone kept using master.

Funnily enough, the frozen branch was often *less stable* than master, because so many bugfixes were making it into master and not into the freeze, and no one had the time to meaningfully patch them back into the freeze, so master was the most stable. I think that stable / testing / frozen branches are mechanisms that only work well past a certain threshold of stability + manpower. Typically new commits have a high potential to make things less stable, but we were at a too volatile stage and most commits actually made master's stability *better*, and I think this is still the case to some extent.

As long as we're low on manpower and/or till we reach a certain level of stability, this won't really work well.
